### ISSUE TITLE
Out of memory after BT

### ISSUE THREAD

**Issue by christopher5106** [facebookresearch/XLM#142]
Hi,

It is very surprising I have an error during the AE step at the start of unsupervised MT. I have trained successfully the EN-FR MLM model before.

```
RuntimeError: CUDA out of memory. Tried to allocate 449.50 MiB (GPU 1; 11.78 GiB total capacity; 9.69 GiB already allocated; 400.81 MiB free; 249.04 MiB cached)
Traceback (most recent call last):
  File "train.py", line 336, in <module>
    main(params)
  File "train.py", line 304, in main
    trainer.bt_step(lang1, lang2, lang3, params.lambda_bt)
  File "XLM/src/trainer.py", line 840, in bt_step
    self.optimize(loss, ['encoder', 'decoder'])
  File "XLM/src/trainer.py", line 130, in optimize
    loss.backward()
  File ".conda/envs/xlm/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File ".conda/envs/xlm/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 479.88 MiB (GPU 0; 11.78 GiB total capacity; 9.91 GiB already allocated; 126.31 MiB free; 190.79 MiB cached)
```

Thank you for your help,

**Comment by christopher5106** [comment]
Changing the batch size has no influence.

**Comment by glample** [comment]
What is your value for `--tokens_per_batch` ? If this is defined, then it overwrites `--batch_size`.

**Comment by christopher5106** [comment]
Great that was what I was looking for. Your answer saved me so much time, thanks!

**Comment by songtaoshi** [comment]
my --tokens_per_batch is set to -1, but I still get the problem. @christopher5106 how do you solve the problem?

**Comment by christopher5106** [comment]
Give it a small value
