### ISSUE TITLE
translate with only pretrained model

### ISSUE THREAD

**Issue by tuyu95** [facebookresearch/XLM#146]
Hello, is there a way to see the output of the pretrained model (MLM or TLM)? I'd like to see what kind of output it produces, and how different pretraining models affect the UNMT. For example, can I translate anything just after pretraining the model?  I use the command like this:

`cat data/processed/de-en/test.de-en.de | \
CUDA_VISIBLE_DEVICES=$devices python3 /home/s1852803/unmt/XLM.ende/XLM/translate.py --exp_name translate \
    --model_path /home/s1852803/unmt/XLM.ende/XLM/best-valid_mlm_ppl.pth \
    --output_path /home/s1852803/unmt/XLM.ende/XLM/output/deen_pre \
    --src_lang de --tgt_lang en --batch_size 16
`

But the error reads that:

INFO - 07/26/19 00:03:17 - 0:00:41 - Supported languages: de, en
Traceback (most recent call last):
  File "/home/s1852803/unmt/XLM.ende/XLM/translate.py", line 150, in <module>
    main(params)
  File "/home/s1852803/unmt/XLM.ende/XLM/translate.py", line 80, in main
    encoder.load_state_dict(reloaded['encoder'])
KeyError: 'encoder'

**Comment by DarshanPatel11** [comment]
@tuyu95 I am facing the same issue. Did you find any solution?

**Comment by fallcat** [comment]
I'm guessing maybe you need to make a dictionary that has 'encoder' and 'decoder' and copy the model parameters into both? So that when you translate, it will recognize
