### ISSUE TITLE
`Dictionary in evaluation data (30145 words) seems different than the one in the pretrained model (52713 words)` when running glue

### ISSUE THREAD

**Issue by hughperkins** [facebookresearch/XLM#165]
when I run glue-xnli.py, I run:

```
python glue-xnli.py --exp_name test_xlm_en_glue --dump_path ./dumped --model_path /tmp/foo.pth --data_path data/processed/XLM_en --transfer_tasks MNLI-m,QNLI,SST-2 --optimizer_e adam,lr=0.000025 --optimizer_p adam,lr=0.000025 --finetune_layers "0:_1" --batch_size 8 --n_epochs 250 --epoch_size 20000 --max_len 256 --max_vocab -1
```

What I expect to happen:
- runs glue evaluation, prints results

What actually happens:
```
FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
INFO - 08/09/19 14:45:42 - 0:00:00 - ============ Initialized logger ============
INFO - 08/09/19 14:45:42 - 0:00:00 - batch_size: 8
                                     command: python glue-xnli.py --exp_name test_xlm_en_glue --dump_path './dumped' --m
odel_path '/tmp/foo.pth' --data_path 'data/processed/XLM_en' --transfer_tasks 'MNLI-m,QNLI,SST-2' --optimizer_e 'adam,lr
=0.000025' --optimizer_p 'adam,lr=0.000025' --finetune_layers '0:_1' --batch_size 8 --n_epochs 250 --epoch_size 20000 --
max_len 256 --max_vocab '-1' --exp_id "tx8ued3b5e"
                                     data_path: data/processed/XLM_en
                                     debug_slurm: False
                                     debug_train: False
                                     dropout: 0
                                     dump_path: ./dumped/test_xlm_en_glue/tx8ued3b5e
                                     epoch_size: 20000
                                     exp_id: tx8ued3b5e
                                     exp_name: test_xlm_en_glue
                                     finetune_layers: 0:_1
                                     group_by_size: False
                                     id2lang: {0: 'en'}
                                     lang2id: {'en': 0}
                                     max_batch_size: 0
                                     max_len: 256
                                     max_vocab: -1
                                     min_count: 0
                                     model_path: /tmp/foo.pth
                                     n_epochs: 250
                                     n_langs: 1
                                     optimizer_e: adam,lr=0.000025
                                     optimizer_p: adam,lr=0.000025
                                     tokens_per_batch: -1
                                     transfer_tasks: ['MNLI-m', 'QNLI', 'SST-2']
                                     weighted_training: False
INFO - 08/09/19 14:45:42 - 0:00:00 - The experiment will be stored in ./dumped/test_xlm_en_glue/tx8ued3b5e

INFO - 08/09/19 14:45:42 - 0:00:00 - Running command: python glue-xnli.py --exp_name test_xlm_en_glue --dump_path './dumped' --model_path '/tmp/foo.pth' --data_path 'data/processed/XLM_en' --transfer_tasks 'MNLI-m,QNLI,SST-2' --optimizer_e 'adam,lr=0.000025' --optimizer_p 'adam,lr=0.000025' --finetune_layers '0:_1' --batch_size 8 --n_epochs 250 --epoch_size 20000 --max_len 256 --max_vocab '-1'

INFO - 08/09/19 14:45:42 - 0:00:00 - Loading data from data/processed/XLM_en/eval/MNLI-m/train.s1.pth ...
INFO - 08/09/19 14:45:42 - 0:00:00 - 9459383 words (30145 unique) in 392702 sentences. 483 unknown words (34 unique) covering 0.01% of the data.
INFO - 08/09/19 14:45:42 - 0:00:00 - Loading data from data/processed/XLM_en/eval/MNLI-m/train.s2.pth ...
INFO - 08/09/19 14:45:42 - 0:00:00 - 4710370 words (30145 unique) in 392702 sentences. 37 unknown words (8 unique) covering 0.00% of the data.
INFO - 08/09/19 14:45:42 - 0:00:00 - Removed 0 empty sentences.
INFO - 08/09/19 14:45:43 - 0:00:00 - Loading data from data/processed/XLM_en/eval/MNLI-m/dev.s1.pth ...
INFO - 08/09/19 14:45:43 - 0:00:00 - 230047 words (30145 unique) in 9815 sentences. 3 unknown words (1 unique) covering 0.00% of the data.
INFO - 08/09/19 14:45:43 - 0:00:00 - Loading data from data/processed/XLM_en/eval/MNLI-m/dev.s2.pth ...
INFO - 08/09/19 14:45:43 - 0:00:00 - 116852 words (30145 unique) in 9815 sentences. 1 unknown words (1 unique) covering 0.00% of the data.
INFO - 08/09/19 14:45:43 - 0:00:01 - Removed 0 empty sentences.
INFO - 08/09/19 14:45:43 - 0:00:01 - Loading data from data/processed/XLM_en/eval/MNLI-m/test.s1.pth ...
INFO - 08/09/19 14:45:43 - 0:00:01 - 233032 words (30145 unique) in 9796 sentences. 18 unknown words (6 unique) covering 0.01% of the data.
INFO - 08/09/19 14:45:43 - 0:00:01 - Loading data from data/processed/XLM_en/eval/MNLI-m/test.s2.pth ...
INFO - 08/09/19 14:45:43 - 0:00:01 - 116450 words (30145 unique) in 9796 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 08/09/19 14:45:43 - 0:00:01 - Removed 0 empty sentences.
Traceback (most recent call last):
  File "glue-xnli.py", line 114, in <module>
    glue.run(task)
  File "/persist/git/XLM/src/evaluation/glue.py", line 84, in run
    "and the same values for max_vocab and min_count.") % (len(self.data['dico']), len(self._embedder.dico)))
Exception: Dictionary in evaluation data (30145 words) seems different than the one in the pretrained model (52713 words). Please verify you used the same dictionary, and the same values for max_vocab and min_count.
```

What have I done wrong so that the dictionaries are different? I followed the instructions at https://github.com/facebookresearch/XLM#i-monolingual-language-model-pretraining-bert as closely as possible.

**Comment by hughperkins** [comment]
Ok, I had to modify `prepare-glue.sh` file to replace the `wget` lines with:
```
cp data/processed/XLM_en/30k/codes $CODES_PATH
cp data/processed/XLM_en/30k/vocab $VOCAB_PATH
```

Technically, the doc does one might need to modify this file, but the potential cause given is if one is not using XLM_en. But I am. And still had to modify it :) And it was not intuitive to me that I would need to modify these wget lines.

**Comment by aconneau** [comment]
What is the model you used? (/tmp/foo.pth, the one that has 52713 words)
