### ISSUE TITLE
Error(s) in loading state_dict for TransformerModel

### ISSUE THREAD

**Issue by jehrodrigues** [facebookresearch/XLM#200]
Is it possible to use the pre-trained model mlm_xnli15_1024.pth instead of mlm_enfr_1024.pth on unmt? This is my train.py:

`python train.py --exp_name unsupMT_enfr \
--dump_path ./dumped/ \
--reload_model 'mlm_xnli15_1024.pth,mlm_xnli15_1024.pth' \
--data_path ./data-en-fr/processed/en-fr/ \
--lgs 'ar-bg-de-el-en-es-fr-hi-ru-sw-th-tr-ur-vi-zh' \
--ae_steps 'en,fr' \
--bt_steps 'en-fr-en,fr-en-fr' \
--word_shuffle 3 \
--word_dropout 0.1 \
--word_blank 0.1  \
--lambda_ae '0:1,100000:0.1,300000:0' \
--encoder_only false  \
--emb_dim 1024  \
--n_layers 6 \
--n_heads 8  \
--dropout 0.1  \
--attention_dropout 0.1  \
--gelu_activation true \
--tokens_per_batch 2000  \
--batch_size 32  \
--bptt 256  \
--optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001  \
--epoch_size 200000  \
--eval_bleu true \
--stopping_criterion 'valid_en-fr_mt_bleu,10' \
--validation_metrics 'valid_en-fr_mt_bleu'`

I preprocessed the corpus with the commands (I deleted the folder before running the command):

`./get-data-nmt.sh --src en --tgt fr --reload_codes codes_xnli_15.txt --reload_vocab vocab_xnli_15.txt`

However, I am getting the following shape error:

INFO - 09/15/19 18:15:28 - 0:00:12 - ============ Data summary
INFO - 09/15/19 18:15:28 - 0:00:12 - Monolingual data   - train -           en:   5000000
INFO - 09/15/19 18:15:28 - 0:00:12 - Monolingual data   - valid -           en:      3000
INFO - 09/15/19 18:15:28 - 0:00:12 - Monolingual data   -  test -           en:      3003
INFO - 09/15/19 18:15:28 - 0:00:12 - Monolingual data   - train -           fr:   5000000
INFO - 09/15/19 18:15:28 - 0:00:12 - Monolingual data   - valid -           fr:      3000
INFO - 09/15/19 18:15:28 - 0:00:12 - Monolingual data   -  test -           fr:      3003
INFO - 09/15/19 18:15:28 - 0:00:12 - Parallel data      - valid -        en-fr:      3000
INFO - 09/15/19 18:15:28 - 0:00:12 - Parallel data      -  test -        en-fr:      3003

INFO - 09/15/19 18:15:39 - 0:00:23 - Reloading encoder from mlm_tlm_xnli15_1024.pth ...
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 236, in main
    encoder, decoder = build_model(params, data['dico'])
  File "/home/jessica/XLM/src/model/__init__.py", line 164, in build_model
    encoder.load_state_dict(enc_reload)
  File "/home/jessica/.conda/envs/xlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
    Unexpected key(s) in state_dict: "attentions.6.q_lin.weight", "attentions.6.q_lin.bias", "attentions.6.k_lin.weight", "attentions.6.k_lin.bias", "attentions.6.v_lin.weight", "attentions.6.v_lin.bias", "attentions.6.out_lin.weight", "attentions.6.out_lin.bias", "attentions.7.q_lin.weight", "attentions.7.q_lin.bias", "attentions.7.k_lin.weight", "attentions.7.k_lin.bias", "attentions.7.v_lin.weight", "attentions.7.v_lin.bias", "attentions.7.out_lin.weight", "attentions.7.out_lin.bias", "attentions.8.q_lin.weight", "attentions.8.q_lin.bias", "attentions.8.k_lin.weight", "attentions.8.k_lin.bias", "attentions.8.v_lin.weight", "attentions.8.v_lin.bias", "attentions.8.out_lin.weight", "attentions.8.out_lin.bias", "attentions.9.q_lin.weight", "attentions.9.q_lin.bias", "attentions.9.k_lin.weight", "attentions.9.k_lin.bias", "attentions.9.v_lin.weight", "attentions.9.v_lin.bias", "attentions.9.out_lin.weight", "attentions.9.out_lin.bias", "attentions.10.q_lin.weight", "attentions.10.q_lin.bias", "attentions.10.k_lin.weight", "attentions.10.k_lin.bias", "attentions.10.v_lin.weight", "attentions.10.v_lin.bias", "attentions.10.out_lin.weight", "attentions.10.out_lin.bias", "attentions.11.q_lin.weight", "attentions.11.q_lin.bias", "attentions.11.k_lin.weight", "attentions.11.k_lin.bias", "attentions.11.v_lin.weight", "attentions.11.v_lin.bias", "attentions.11.out_lin.weight", "attentions.11.out_lin.bias", "layer_norm1.6.weight", "layer_norm1.6.bias", "layer_norm1.7.weight", "layer_norm1.7.bias", "layer_norm1.8.weight", "layer_norm1.8.bias", "layer_norm1.9.weight", "layer_norm1.9.bias", "layer_norm1.10.weight", "layer_norm1.10.bias", "layer_norm1.11.weight", "layer_norm1.11.bias", "ffns.6.lin1.weight", "ffns.6.lin1.bias", "ffns.6.lin2.weight", "ffns.6.lin2.bias", "ffns.7.lin1.weight", "ffns.7.lin1.bias", "ffns.7.lin2.weight", "ffns.7.lin2.bias", "ffns.8.lin1.weight", "ffns.8.lin1.bias", "ffns.8.lin2.weight", "ffns.8.lin2.bias", "ffns.9.lin1.weight", "ffns.9.lin1.bias", "ffns.9.lin2.weight", "ffns.9.lin2.bias", "ffns.10.lin1.weight", "ffns.10.lin1.bias", "ffns.10.lin2.weight", "ffns.10.lin2.bias", "ffns.11.lin1.weight", "ffns.11.lin1.bias", "ffns.11.lin2.weight", "ffns.11.lin2.bias", "layer_norm2.6.weight", "layer_norm2.6.bias", "layer_norm2.7.weight", "layer_norm2.7.bias", "layer_norm2.8.weight", "layer_norm2.8.bias", "layer_norm2.9.weight", "layer_norm2.9.bias", "layer_norm2.10.weight", "layer_norm2.10.bias", "layer_norm2.11.weight", "layer_norm2.11.bias". 
    size mismatch for embeddings.weight: copying a param with shape torch.Size([95000, 1024]) from checkpoint, the shape in current model is torch.Size([121328, 1024]).
    size mismatch for pred_layer.proj.weight: copying a param with shape torch.Size([95000, 1024]) from checkpoint, the shape in current model is torch.Size([121328, 1024]).
    size mismatch for pred_layer.proj.bias: copying a param with shape torch.Size([95000]) from checkpoint, the shape in current model is torch.Size([121328]).
(xlm) jessica@pytorch-1-vm:~/XLM$

@glample @aconneau

**Comment by glample** [comment]
Hi,

Can you try to add `--max_vocab 95000` to your command?

**Comment by jehrodrigues** [comment]
Hi @glample , adding **--max_vocab** solved this problem. I am now testing unmt for en-pt with the pre-trained model mlm_17_1280.pth. My train.py is as follows:

`python train.py --exp_name unsupMT_enpt \
--dump_path ./dumped/ \
--reload_model 'mlm_17_1280.pth,mlm_17_1280.pth' \
--data_path ./data-en-pt/processed/en-pt/ \
--lgs 'en-fr-es-de-it-pt-nl-sv-pl-ru-ar-tr-zh-ja-ko-hi-vi' \
--max_vocab 200000 \
--ae_steps 'en,pt' \
--bt_steps 'en-pt-en,pt-en-pt' \
--word_shuffle 3 \
--word_dropout 0.1 \
--word_blank 0.1  \
--lambda_ae '0:1,100000:0.1,300000:0' \
--encoder_only false  \
--emb_dim 1280  \
--n_layers 16 \
--n_heads 16  \
--dropout 0.1  \
--attention_dropout 0.1  \
--gelu_activation true \
--tokens_per_batch 2000  \
--batch_size 32  \
--bptt 256  \
--optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001  \
--epoch_size 200000  \
--eval_bleu true \
--stopping_criterion 'valid_en-pt_mt_bleu,10' \
--validation_metrics 'valid_en-pt_mt_bleu'`

My preprocessing:

`./get-data-nmt.sh --src en --tgt pt --reload_codes codes_xnli_17.txt --reload_vocab vocab_xnli_17.txt`

This is the error:

INFO - 09/15/19 23:52:04 - 0:00:18 - ============ Data summary
INFO - 09/15/19 23:52:04 - 0:00:18 - Monolingual data   - train -           en:   5000000
INFO - 09/15/19 23:52:04 - 0:00:18 - Monolingual data   - valid -           en:      3075
INFO - 09/15/19 23:52:04 - 0:00:18 - Monolingual data   -  test -           en:      3000
INFO - 09/15/19 23:52:04 - 0:00:18 - Monolingual data   - train -           pt:   5000000
INFO - 09/15/19 23:52:04 - 0:00:18 - Monolingual data   - valid -           pt:      3075
INFO - 09/15/19 23:52:04 - 0:00:18 - Monolingual data   -  test -           pt:      3000
INFO - 09/15/19 23:52:04 - 0:00:18 - Parallel data      - valid -        en-pt:      3075
INFO - 09/15/19 23:52:04 - 0:00:18 - Parallel data      -  test -        en-pt:      3000

INFO - 09/15/19 23:52:29 - 0:00:43 - Reloading encoder from mlm_17_1280.pth ...
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 236, in main
    encoder, decoder = build_model(params, data['dico'])
  File "/home/jessica/XLM/src/model/__init__.py", line 164, in build_model
    encoder.load_state_dict(enc_reload)
  File "/home/jessica/.conda/envs/xlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
  Missing key(s) in state_dict: "lang_embeddings.weight".

lang_embeddings.weight is related to **--lgs** right?

**Comment by glample** [comment]
I think this is because this model was trained without the language embeddings. You can simply do `encoder.load_state_dict(enc_reload, strict=False)` and check that `lang_embeddings.weight` was the only missing component, and it should be fine. This is not a critical parameter and the model will learn them quickly for the unsupervised machine translation task.

**Comment by jehrodrigues** [comment]
Hi @glample ! Thank you for the solution. Apparently now the execution is going to the training. I am using a Tesla T4 2 GPUs (16GB memory each) and am having the error below:

(xlm) jessica@pytorch-1-vm:~/XLM$ tail -f nohup.out 
FAISS library was not found.
FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
FAISS not available. Switching to standard nearest neighbors search implementation.
SLURM job: False
SLURM job: False
RANK:  1
RANK:  0
0 - Number of nodes: 1
1 - Number of nodes: 1
0 - Node ID        : 0
1 - Node ID        : 0
0 - Local rank     : 0
1 - Local rank     : 1
0 - Global rank    : 0
1 - Global rank    : 1
0 - World size     : 2
1 - World size     : 2
0 - GPUs per node  : 2
1 - GPUs per node  : 2
0 - Master         : True
1 - Master         : False
0 - Multi-node     : False
1 - Multi-node     : False
0 - Multi-GPU      : True
1 - Multi-GPU      : True
0 - Hostname       : pytorch-1-vm
1 - Hostname       : pytorch-1-vm
Initializing PyTorch distributed ...
Initializing PyTorch distributed ...
INFO - 09/17/19 16:12:54 - 0:00:00 - ============ Initialized logger ============
INFO - 09/17/19 16:12:54 - 0:00:00 - accumulate_gradients: 1
                                     ae_steps: ['en', 'pt']
.
.
.
INFO - 09/17/19 16:14:16 - 0:01:21 - Number of parameters (encoder): 571696960
INFO - 09/17/19 16:14:16 - 0:01:21 - Number of parameters (decoder): 676677440
INFO - 09/17/19 16:14:16 - 0:01:23 - Number of parameters (encoder): 571696960
INFO - 09/17/19 16:14:16 - 0:01:23 - Number of parameters (decoder): 676677440
INFO - 09/17/19 16:14:18 - 0:01:23 - Found 0 memories.
INFO - 09/17/19 16:14:18 - 0:01:23 - Found 32 FFN.
INFO - 09/17/19 16:14:18 - 0:01:24 - Found 0 memories.
INFO - 09/17/19 16:14:18 - 0:01:24 - Found 32 FFN.
INFO - 09/17/19 16:14:18 - 0:01:23 - Found 682 parameters in model.
INFO - 09/17/19 16:14:18 - 0:01:23 - Using nn.parallel.DistributedDataParallel ...
INFO - 09/17/19 16:14:18 - 0:01:24 - Found 682 parameters in model.
INFO - 09/17/19 16:14:18 - 0:01:24 - Using nn.parallel.DistributedDataParallel ...
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 327, in <module>
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 243, in main
    main(params)
  File "train.py", line 243, in main
    trainer = EncDecTrainer(encoder, decoder, data, params)
  File "/home/jessica/XLM/src/trainer.py", line 814, in __init__
    trainer = EncDecTrainer(encoder, decoder, data, params)
  File "/home/jessica/XLM/src/trainer.py", line 814, in __init__
    super().__init__(data, params)
    super().__init__(data, params)
  File "/home/jessica/XLM/src/trainer.py", line 66, in __init__
  File "/home/jessica/XLM/src/trainer.py", line 66, in __init__
    self.set_optimizers()
    self.set_optimizers()
  File "/home/jessica/XLM/src/trainer.py", line 165, in set_optimizers
  File "/home/jessica/XLM/src/trainer.py", line 165, in set_optimizers
    self.optimizers['model'] = get_optimizer(self.parameters['model'], params.optimizer)
  File "/home/jessica/XLM/src/optim.py", line 270, in get_optimizer
    self.optimizers['model'] = get_optimizer(self.parameters['model'], params.optimizer)
  File "/home/jessica/XLM/src/optim.py", line 270, in get_optimizer
    return optim_fn(parameters, **optim_params)
    return optim_fn(parameters, **optim_params)
  File "/home/jessica/XLM/src/optim.py", line 112, in __init__
  File "/home/jessica/XLM/src/optim.py", line 112, in __init__
    weight_decay=weight_decay,
    weight_decay=weight_decay,
  File "/home/jessica/XLM/src/optim.py", line 40, in __init__
  File "/home/jessica/XLM/src/optim.py", line 40, in __init__
    state['exp_avg_sq'] = torch.zeros_like(p.data)
    state['exp_avg_sq'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 6.25 MiB (GPU 0; 14.73 GiB total capacity; 13.23 GiB already allocated; 7.94 MiB free; 998.00 KiB cached)
RuntimeError: CUDA out of memory. Tried to allocate 6.25 MiB (GPU 1; 14.73 GiB total capacity; 13.23 GiB already allocated; 7.94 MiB free; 998.00 KiB cached)

Is there anything I can do to train my model? I also tested on a Tesla V100 4 GPUs and got the same problem.

**Comment by glample** [comment]
You can try to reduce either the batch size: `--batch_size 16` or reduce the number of tokens per batch: `--tokens_per_batch 1000`

**Comment by gunnxx** [comment]
So, training on multiple-GPUs or multiple-nodes is only meant to speed up the training? It can't handle the case where model doesn't fit into single memory?

**Comment by leiterenato** [comment]
Hi @glample,
I reproduced the scenario with --batch_size 1 and --tokens_per_batch 100, but I got the same 'CUDA out of memory' message.
Would it be possible to load the model to CPU, instead of GPU memory?
Maybe change the `torch.load(...)` to CPU and train on GPU.

Here is the clone with the code we are using, https://github.com/jehrodrigues/xlm-nmt, in case you want to take a look.
Thank you very much!

**Comment by 645709712** [comment]
@jehrodrigues Hello I encountered the same problem of insufficient GPU space. Can you tell me how to solve this problem?

**Comment by 645709712** [comment]
@leiterenato Hello I encountered the same problem of insufficient GPU space. I would like to know if your xlm-nmt project can solve this problem, and if so, what optimizations have been made. Looking forward to your reply, thank you very much

**Comment by leiterenato** [comment]
@645709712 Unfortunately I could not manage to solve this issue. For now I am using an implementation of XLM with HuggingFace API.

**Comment by 645709712** [comment]
@leiterenato Ok.Thank you .I have also abandoned this model. It ’s too big. At far as I concerned, there is no other way to solve this problem besides upgrading the hardware.
