### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Evandernyoni** [facebookresearch/XLM#202]
When I run python train.py in colab I get the following error:

'''
FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
Traceback (most recent call last):
  File "train.py", line 323, in <module>
    check_data_params(params)
  File "/content/XLM/src/data/loader.py", line 233, in check_data_params
    assert os.path.isdir(params.data_path), params.data_path
AssertionError

'''

I followed the instructions at https://github.com/facebookresearch/XLM#iii-applications-supervised--unsupervised-mt

**Comment by aconneau** [comment]
It means that the path "data_path" to your directory doesn't exist (mostly likely ./data/processed/en-fr/), so maybe you didn't download/preprocess the data?
