### ISSUE TITLE
Parallel training of unsupervised mt model fails

### ISSUE THREAD

**Issue by alexandra-chron** [facebookresearch/XLM#211]
Running

```
export CUDA_VISIBLE_DEVICES=2,3; export NGPU=2; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py --exp_name unsup_mt --dump_path ./dumped/ --data_path /mounts/data/proj/achron/XLM/data/processed/de-en/ --lgs en-de --ae_steps en,de --bt_steps en-de-en,de-en-de --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae 0:1,100000:0.1,300000:0 --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 200 --batch_size 32 --bptt 128 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 200000 --eval_bleu true --stopping_criterion valid_en-de_mt_bleu,10 --validation_metrics valid_en-de_mt_bleu --reload_model mlm_ende_1024.pth,mlm_ende_1024.pth
```

with pytorch==1.2.0 from conda environment (python==3.6.9) I get this error after the data iterators are created:

```
INFO - 10/07/19 13:31:03 - 0:00:22 - ============ Starting epoch 0 ... ============
INFO - 10/07/19 13:31:03 - 0:00:22 - Creating new training data iterator (ae,de) ...
INFO - 10/07/19 13:31:05 - 0:00:24 - ============ Starting epoch 0 ... ============
INFO - 10/07/19 13:31:05 - 0:00:24 - Creating new training data iterator (ae,en) ...
INFO - 10/07/19 13:31:19 - 0:00:38 - Creating new training data iterator (ae,de) ...
INFO - 10/07/19 13:31:19 - 0:00:38 - Creating new training data iterator (ae,en) ...
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 280, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/mounts/Users/cisintern/achron/XLM-no-changes/src/trainer.py", line 851, in mt_step
    enc1 = self.encoder('fwd', x=x1, lengths=len1, langs=langs1, causal=False)
  File "/opt/softw/Miniconda3/envs/nmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/softw/Miniconda3/envs/nmt/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 459, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /opt/conda/conda-bld/pytorch_1565272279342/work/torch/csrc/distributed/c10d/reducer.cpp:518)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f66c2c02e37 in /opt/softw/Miniconda3/envs/nmt/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x7b7 (0x7f66f41dd497 in /opt/softw/Miniconda3/envs/nmt/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x699443 (0x7f66f41cc443 in /opt/softw/Miniconda3/envs/nmt/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1c8316 (0x7f66f3cfb316 in /opt/softw/Miniconda3/envs/nmt/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyCFunction_FastCallDict + 0x154 (0x55c05fb09c54 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #5: <unknown function> + 0x199c0e (0x55c05fb91c0e in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x30a (0x55c05fbb475a in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #7: <unknown function> + 0x192e66 (0x55c05fb8ae66 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #8: _PyFunction_FastCallDict + 0x3d8 (0x55c05fb8c598 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #9: _PyObject_FastCallDict + 0x26f (0x55c05fb0a01f in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #10: _PyObject_Call_Prepend + 0x63 (0x55c05fb0eaa3 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #11: PyObject_Call + 0x3e (0x55c05fb09a5e in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x19e7 (0x55c05fbb5e37 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #13: <unknown function> + 0x192e66 (0x55c05fb8ae66 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #14: _PyFunction_FastCallDict + 0x3d8 (0x55c05fb8c598 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #15: _PyObject_FastCallDict + 0x26f (0x55c05fb0a01f in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #16: _PyObject_Call_Prepend + 0x63 (0x55c05fb0eaa3 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #17: PyObject_Call + 0x3e (0x55c05fb09a5e in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #18: <unknown function> + 0x16b371 (0x55c05fb63371 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #19: _PyObject_FastCallDict + 0x8b (0x55c05fb09e3b in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #20: _PyObject_FastCallKeywords + 0xaa (0x55c05fb8c18a in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #21: <unknown function> + 0x199c0e (0x55c05fb91c0e in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x10cc (0x55c05fbb551c in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #23: <unknown function> + 0x193c5b (0x55c05fb8bc5b in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #24: <unknown function> + 0x199b95 (0x55c05fb91b95 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x30a (0x55c05fbb475a in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #26: <unknown function> + 0x193c5b (0x55c05fb8bc5b in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #27: <unknown function> + 0x199b95 (0x55c05fb91b95 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x30a (0x55c05fbb475a in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #29: PyEval_EvalCodeEx + 0x329 (0x55c05fb8c9b9 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #30: PyEval_EvalCode + 0x1c (0x55c05fb8d75c in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #31: <unknown function> + 0x215744 (0x55c05fc0d744 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #32: PyRun_FileExFlags + 0xa1 (0x55c05fc0db41 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #33: PyRun_SimpleFileExFlags + 0x1c3 (0x55c05fc0dd43 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #34: Py_Main + 0x613 (0x55c05fc11833 in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #35: main + 0xee (0x55c05fadb88e in /opt/softw/Miniconda3/envs/nmt/bin/python)
frame #36: __libc_start_main + 0xe7 (0x7f670a503b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #37: <unknown function> + 0x1c3160 (0x55c05fbbb160 in /opt/softw/Miniconda3/envs/nmt/bin/python)
```

I cannot seem to find the way to fix it. This only happens at the unsupervised MT training (I trained an MLM on multiple gpus without a problem). It also only happens on parallel training,  the model is running fine on 1 gpu.

Any ideas?
thanks in advance

**Comment by alexandra-chron** [comment]
For anyone who might have this issue, I solved it like this:
https://github.com/facebookresearch/XLM/blob/master/src/trainer.py#L63 changed this line to:

setattr(self, name, nn.parallel.DistributedDataParallel(getattr(self, name), device_ids=[params.local_rank], output_device=params.local_rank, broadcast_buffers=True,
                                                                        find_unused_parameters=True))

**Comment by fallcat** [comment]
@alexandra-chron Hi! Were you able to get it trained and translate with reasonable BLEU scores? I'm really stuck at getting it trained properly with multi-GPU and I'm wondering if you would be able to share your trained model. Thank you so much in advance!

**Comment by alexandra-chron** [comment]
@fallcat hi, I have been able to train a model yes. What kind of problem do you have? I have only trained a small-scale en-de model, with <1M de data, so I do not think it would be useful to you.

**Comment by fallcat** [comment]
@alexandra-chron Thanks! I have found a trained model here https://github.com/Hansxsourse/XLM-UNMT-Models so I think I'm fine. Whenever I train on multi-GPU, it hangs when initializing apex's distributed feature
