### ISSUE TITLE
KeyError: 'encoder'

### ISSUE THREAD

**Issue by Dod-o** [facebookresearch/XLM#212]
hi，

I use  monolingual and bilingual data during pre-train (MLM + TLM), the command is as follows:
```
OUTPATH=../data/processed/XLM_de_en/32k
export NGPU=4; python -m torch.distributed.launch --nproc_per_node=$NGPU ../train.py \
--exp_name xlm_de_en \
--dump_path ./dumped \
--data_path $OUTPATH \
--lgs 'de-en' \
--clm_steps '' \
--mlm_steps 'de,en,de-en' \
--emb_dim 1024 \
--n_layers 6 \
--n_heads 8 \
--dropout 0.1 \
--attention_dropout 0.1 \
--gelu_activation true \
--batch_size 32 \
--bptt 256 \
--optimizer adam,lr=0.0001 \
--epoch_size 300000 \
--max_epoch 100000 \
--validation_metrics _valid_mlm_ppl \
--stopping_criterion _valid_mlm_ppl,25
```

the pre-training haven't finished yet, and I'd like to do a translation test with the current checkpoint. I use this command:

```
python ../translate.py \
--dump_path dumped \
--exp_name mt_de_en \
--model_path dumped/xlm_de_en/c958ztz2l5/best-valid_mlm_ppl.pth \
--output_path output \
--src_lang de \
--tgt_lang en

```

but I got the error:
```
FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
INFO - 10/07/19 15:48:35 - 0:00:00 - ============ Initialized logger ============
INFO - 10/07/19 15:48:35 - 0:00:00 - batch_size: 32
                                     command: python ../translate.py --dump_path dumped --exp_name mt_de_en --model_path 'dumped/xlm_de_en/c958ztz2l5/best-valid_mlm_ppl.pth' --output_path output --src_lang de --tgt_lang en --exp_id "f1yi7u5d55"
                                     dump_path: dumped/mt_de_en/f1yi7u5d55
                                     exp_id: f1yi7u5d55
                                     exp_name: mt_de_en
                                     model_path: dumped/xlm_de_en/c958ztz2l5/best-valid_mlm_ppl.pth
                                     output_path: output
                                     src_lang: de
                                     tgt_lang: en
INFO - 10/07/19 15:48:35 - 0:00:00 - The experiment will be stored in dumped/mt_de_en/f1yi7u5d55
                                     
INFO - 10/07/19 15:48:35 - 0:00:00 - Running command: python ../translate.py --dump_path dumped --exp_name mt_de_en --model_path 'dumped/xlm_de_en/c958ztz2l5/best-valid_mlm_ppl.pth' --output_path output --src_lang de --tgt_lang en

INFO - 10/07/19 15:48:43 - 0:00:08 - Supported languages: de, en
Traceback (most recent call last):
  File "../translate.py", line 148, in <module>
    main(params)
  File "../translate.py", line 84, in main
    encoder.load_state_dict(reloaded['encoder'])
KeyError: 'encoder'
```

What should I do? is there any other way? I just want to be able to get the translated text.

thanks~

**Comment by danielcamara** [comment]
Hi,
 we are having the same problem, and we don' t know why. On the  ipython notebook demo it is used 'model'  instead of  'encode' and 'decode'.... However, the decoding part is not shown!

Did you find a solution?

Best regards, 

-- Daniel
