### ISSUE TITLE
Use XLM to train BERT on a large dataset 

### ISSUE THREAD

**Issue by formiel** [facebookresearch/XLM#213]
Hi, thank you so much again for releasing the code!

I'm trying to train BERT on a large dataset (of around 80GB after being binarised). Hence, the data could not be loaded into the memory at one time using `torch.load` https://github.com/facebookresearch/XLM/blob/15d4c188c918b08ec7075fb30b8af27a14c4ddb8/src/data/loader.py#L68.

Therefore, I would like to ask if we could have a way to get around this issue using the existing code or if it is necessary to revise the code in order to train the model on a large dataset.

Many thanks in advance for your time and your help!

**Comment by glample** [comment]
I assume you are using multi-GPU training? In that case, you can have a look at:
https://github.com/facebookresearch/XLM/blob/master/src/data/loader.py#L61-L65

And split your training set into several files. Like, if you have 8 GPU, instead of having `train.en.pth`, you can have `train.en.0.pth`, `train.en.1.pth`, `train.en.2.pth`, etc. up to `train.en.7.pth`. This way, each process will load 1/8 of the dataset (which will increases a lot the loading time, and memory usage).

**Comment by formiel** [comment]
Thank you so much for your quick response!!! Is this also applicable to multiple nodes multiple GPUs training on Slurm?

**Comment by glample** [comment]
Yes. If you have 64 GPU you can split your dataset into 64 files and replace `local_rank` by `global_rank` in https://github.com/facebookresearch/XLM/blob/master/src/data/loader.py#L62

But then if you decide to only use 32 GPU you will need to make another chunk of 32 training shards, which is not very convenient. I like splitting in 8, this way as long as you use N*8 GPUs you can simply use `local_rank` which will be between 0 and 7 on each machine.

**Comment by formiel** [comment]
Thank you so much for your kind help!!!

I've split data and successfully run the training on 1 node (including 4 GPUs) in a server not using Slurm. However, when I run it on 2 nodes (each node including 4GPUs as well) on the server using Slurm, there was `Runtime error` of `Broken pipe` and `Connection reset by peer` as below.

```
Traceback (most recent call last):
  File "train.py", line 367, in <module>
    main(params)
  File "train.py", line 253, in main
    trainer = SingleTrainer(model, data, params)
  File "/home/BERT/code/src/trainer.py", line 831, in __init__
    super().__init__(data, params)
  File "/home/BERT/code/src/trainer.py", line 75, in __init__
    setattr(self, name, apex.parallel.DistributedDataParallel(getattr(self, name), delay_allreduce=True))
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/apex/parallel/distributed.py", line 253, in __init__
    flat_dist_call([param.data for param in self.module.parameters()], dist.broadcast, (0,) )
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/apex/parallel/distributed.py", line 75, in flat_dist_call
    apply_flat_dist_call(bucket, call, extra_args)
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/apex/parallel/distributed.py", line 41, in apply_flat_dist_call
    call(coalesced, *extra_args)
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 806, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Broken pipe
```
```
Traceback (most recent call last):
  File "train.py", line 367, in <module>
    main(params)
  File "train.py", line 253, in main
    trainer = SingleTrainer(model, data, params)
  File "/home/BERT/code/src/trainer.py", line 831, in __init__
    super().__init__(data, params)
  File "/home/BERT/code/src/trainer.py", line 75, in __init__
    setattr(self, name, apex.parallel.DistributedDataParallel(getattr(self, name), delay_allreduce=True))
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/apex/parallel/distributed.py", line 253, in __init__
    flat_dist_call([param.data for param in self.module.parameters()], dist.broadcast, (0,) )
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/apex/parallel/distributed.py", line 75, in flat_dist_call
    apply_flat_dist_call(bucket, call, extra_args)
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/apex/parallel/distributed.py", line 41, in apply_flat_dist_call
    call(coalesced, *extra_args)
  File ".../anaconda-py3/2019.03/envs/pytorch-1.1/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 806, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Connection reset by peer
```
I thought it may be because of the connection problem between the nodes. So I tried to run the model on 2 nodes using a smaller dataset without splitting the data and there was no such problem.

Could you please help me on this issue?

Thank you so so much for your support!!!

**Comment by glample** [comment]
Are you sure the error above happens only when you use a large dataset? The error seems very unrelated. This is like if having a lot of RAM usage because of the dataset size could be responsible for the PyTorch distributed failure, but I don't understand how.

**Comment by formiel** [comment]
Thank you so much for your quick response!!!

I've just split a smaller dataset (4GB) into 4 `.pth` files and train on 2 nodes on the server using Slurm and there is no such problem. In summary, I tried the following:

1. Split the large dataset into 4 files and run on 1 node (this server where I run the script does not use Slurm): Successfully.
2. Split the large dataset into 4 files and run on 2 nodes on the server using Slurm (these 2 servers are totally different in infrastructure): Not successfully.
3. Split the large dataset into 4 files and run on 1 node on the server using Slurm: Not successfully.
4. Split the smaller dataset into 4 files and run on 2 nodes on the server using Slurm: Successfully.

So I guess this problem arises when I use the large dataset. I've checked the memory limit of each server and there is something unusual because the capability of the server with Slurm is much larger than the other server...  If I could not solve this issue then I will split the large dataset into 32 files to train on 8 complete nodes and use `global_rank` to index the files as you mentioned previously. I will let you know about the results.

Thank you so much again for your very kind help!!

**Comment by formiel** [comment]
Thank you so much for your help!!! The problem indeed arises from RAM usage as you said previously. So I used `global_rank` to split data into smaller portions so that each portion could fit into a process.

Thanks to your help I could load the data and start the training now. However, the script gets stuck at the end of the first epoch and fails to proceed any further although I waited for quite a long time. I tested using a small `epoch_size` of 200 so one epoch is pretty fast.

This is the output of the master log and other train logs look almost the same.
```
INFO - 10/16/19 11:16:45 - 0:00:15 - ============ Starting epoch 0 ... ============
INFO - 10/16/19 11:16:45 - 0:00:15 - Creating new training data iterator (pred,fr) ...
INFO - 10/16/19 11:16:49 - 0:00:19 -       5 -   40.15 sent/s -  3073.60 words/s - MLM-fr: 11.5410 -  - model LR: 1.9998e-07
INFO - 10/16/19 11:16:51 - 0:00:21 - ============ End of epoch 0 ============
```
I run the following command in the submission script to Slurm after requesting for resources with `SBATCH`.
```
srun python train.py \
    --exp_name $EXPNAME \
    --dump_path $OUTPUTPATH \
    --data_path $DATAPATH \
    --amp 1 \
    --lgs 'en' \
    --clm_steps '' \
    --mlm_steps 'en' \
    --emb_dim $EMB_DIM \
    --n_layers $LAYERS \
    --n_heads $HEADS \
    --dropout 0.1 \
    --attention_dropout 0.1 \
    --gelu_activation true \
    --batch_size $BATCH_SIZE \
    --bptt $MAX_LEN \
    --optimizer adam_inverse_sqrt,lr=0.0006,warmup_updates=24000,beta1=0.9,beta2=0.98,weight_decay=0.01,eps=0.000001 \
    --epoch_size $EPOCH_SIZE \
    --max_epoch 100000 \
    --validation_metrics _valid_en_mlm_ppl \
    --stopping_criterion _valid_en_mlm_ppl,20 \
    --fp16 true \
    --accumulate_gradients $ACCUM_GRAD \
    --word_mask_keep_rand '0.8,0.1,0.1' \
    --word_pred '0.15' \
    --master_port 20000
```
Could you please share if you have any ideas of what the problem could be?

In addition, I'm confused about the role of `torch.distributed` package in `slurm.py` script below in gathering information across all GPUs devices of all the nodes to transfer to the master node. I suppose that Slurm will handle the information transferring between the nodes and `torch.distributed` will handle the communication between GPUs in one node (or between the nodes if the server does not use Slurm). Is that right?

https://github.com/facebookresearch/XLM/blob/ec48f7397bc5afb6c03e9a8e6a5a4e271682ed4b/src/slurm.py#L156-L170 

And also could you please help me explain if the data is split in advance and each GPU sees a fixed portion of the data, what would be the role of `DistributedDataParallel` module in the `trainer.py` in this case? I thought that this module is to implement data paralellism across GPUs of one machine by scattering the input data along the batch dimension. However, we have split the data already so I don't know what the mechanism would be in this case.

https://github.com/facebookresearch/XLM/blob/ec48f7397bc5afb6c03e9a8e6a5a4e271682ed4b/src/trainer.py#L68-L74

Thank you so much for your tremendous support!!!
