### ISSUE TITLE
Use xlm train clm model error

### ISSUE THREAD

**Issue by remName** [facebookresearch/XLM#216]
Hi, I use xlm to trian clm model but get the following error
This is my shell:

```
export CUDA_VISIBLE_DEVICES=0,1
export CUDA_LAUNCH_BLOCKING=1
export NGPU=2;

nohup  python -m torch.distributed.launch --nproc_per_node=$NGPU train.py \
	 --exp_name enzh_clm_fp16 \
	 --exp_id  test_one \
	 --dump_path ./dumped/ \
	 --data_path ./enzh_data/processed/en-zh/ \
	 --lgs 'en-zh' \
	 --clm_steps 'en,zh' \
	 --emb_dim 1024 \
	 --fp16 true \
	 --n_layers 7 \
	 --n_heads 8 \
	 --dropout 0.1 \
	 --attention_dropout 0.1 \
	 --gelu_activation true \
	 --batch_size 128 \
	 --bptt 256 \
	 --optimizer adam,lr=0.0001 \
	 --epoch_size 200000 \
	 --validation_metrics _valid_clm_ppl \
	 --stopping_criterion _valid_clm_ppl,20 >> clm.log 2>&1 &
```
but I get the error:

```
INFO - 10/11/19 12:04:12 - 0:00:22 - ============ Starting epoch 0 ... ============
INFO - 10/11/19 12:04:12 - 0:00:22 - Creating new training data iterator (causal,en) ...
INFO - 10/11/19 12:04:12 - 0:00:22 - ============ Starting epoch 0 ... ============
INFO - 10/11/19 12:04:12 - 0:00:22 - Creating new training data iterator (causal,zh) ...
/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/_reduction.py:15: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=110 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 278, in main
    trainer.clm_step(lang1, lang2, params.lambda_clm)
  File "/home/test/xlm/src/trainer.py", line 587, in clm_step
    _, loss = model('predict', tensor=tensor, pred_mask=pred_mask, y=y, get_scores=False)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/apex/parallel/distributed.py", line 476, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/xlm/src/model/transformer.py", line 313, in forward
    return self.predict(**kwargs)
  File "/home/test/xlm/src/model/transformer.py", line 415, in predict
    scores, loss = self.pred_layer(masked_tensor, y, get_scores)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/xlm/src/model/transformer.py", line 132, in forward
    loss = F.cross_entropy(scores, y, reduction='elementwise_mean')
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110
/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/_reduction.py:15: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=110 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 278, in main
    trainer.clm_step(lang1, lang2, params.lambda_clm)
  File "/home/test/xlm/src/trainer.py", line 587, in clm_step
    _, loss = model('predict', tensor=tensor, pred_mask=pred_mask, y=y, get_scores=False)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/apex/parallel/distributed.py", line 476, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/xlm/src/model/transformer.py", line 313, in forward
    return self.predict(**kwargs)
  File "/home/test/xlm/src/model/transformer.py", line 415, in predict
    scores, loss = self.pred_layer(masked_tensor, y, get_scores)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/xlm/src/model/transformer.py", line 132, in forward
    loss = F.cross_entropy(scores, y, reduction='elementwise_mean')
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110
terminate called without an active exception
terminate called without an active exception
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/test/anaconda3/envs/pytorch/bin/python', '-u', 'train.py', '--local_rank=0', '--exp_name', 'enzh_clm_fp16', '--exp_id', 'test_one', '--dump_path', './dumped/', '--data_path', './enzh_data/processed/en-zh/', '--lgs', 'en-zh', '--clm_steps', 'en,zh', '--emb_dim', '1024', '--fp16', 'true', '--n_layers', '7', '--n_heads', '8', '--dropout', '0.1', '--attention_dropout', '0.1', '--gelu_activation', 'true', '--batch_size', '128', '--bptt', '256', '--optimizer', 'adam,lr=0.0001', '--epoch_size', '200000', '--validation_metrics', '_valid_clm_ppl', '--stopping_criterion', '_valid_clm_ppl,20']' died with <Signals.SIGABRT: 6>.
```

**Comment by remName** [comment]
I am sorry for this. this error is due to my too large batchsize, after I reduced  the batchsize，xlm runs normally.
