### ISSUE TITLE
Multi-GPU training get stuck after one mini-batch

### ISSUE THREAD

**Issue by JianLiu91** [facebookresearch/XLM#223]
I have made the following changes:
`change to encoder = TransformerModel(params, dico, is_encoder=True, with_output=False) at line.
change to encoder.load_state_dict(enc_reload, strict=False) at line.`

But only after one mini-batch, it says:

> INFO - 10/24/19 12:10:33 - 0:00:29 - Creating new training data iterator (bt,fr) ...
INFO - 10/24/19 12:10:33 - 0:00:29 - Creating new training data iterator (bt,fr) ...
INFO - 10/24/19 12:10:54 - 0:00:49 -       5 -   20.22 sent/s -   563.79 words/s - AE-en: 13.9863 || AE-fr: 13.6750 || BT-en-fr-en: 11.6189 || BT-fr-en-fr: 11.7534 -  - model LR: 5.9950e-07
INFO - 10/24/19 12:10:54 - 0:00:49 -       5 -   23.04 sent/s -   560.06 words/s - AE-en: 13.3414 || AE-fr: 13.7342 || BT-en-fr-en: 11.8318 || BT-fr-en-fr: 11.8245 -  - model LR: 5.9950e-07
INFO - 10/24/19 12:10:54 - 0:00:49 -       5 -   24.93 sent/s -   559.75 words/s - AE-en: 13.5089 || AE-fr: 13.9254 || BT-en-fr-en: 11.6974 || BT-fr-en-fr: 11.7821 -  - model LR: 5.9950e-07
INFO - 10/24/19 12:10:54 - 0:00:49 -       5 -   27.80 sent/s -   560.75 words/s - AE-en: 13.5937 || AE-fr: 13.4597 || BT-en-fr-en: 11.7517 || BT-fr-en-fr: 11.7159 -  - model LR: 5.9950e-07
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 288, in main
    trainer.bt_step(lang1, lang2, lang3, params.lambda_bt)
  File "/home/jliu/research/XLM/src/trainer.py", line 902, in bt_step
    x2, len2 = _decoder.generate(enc1, len1, lang2_id, max_len=int(1.3 * len1.max().item() + 5))
  File "/home/jliu/research/XLM/src/model/transformer.py", line 497, in generate
    cache=cache
  File "/home/jliu/research/XLM/src/model/transformer.py", line 326, in forward
    return self.fwd(**kwargs)
  File "/home/jliu/research/XLM/src/model/transformer.py", line 397, in fwd
    tensor = tensor + attn
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f72bfa0c813 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x16126 (0x7f72bfc47126 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x16b11 (0x7f72bfc47b11 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7f72bf9fcf0d in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: c10d::Reducer::~Reducer() + 0x449 (0x7f730bb681b9 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

**Comment by glample** [comment]
Can you run the same command, with `CUDA_LAUNCH_BLOCKING=1 python ...` instead? This should give a more accurate stack trace error.
Also, how long are your sentences? This looks like some kind of issue that you would get when you have sentences longer than `N_MAX_POSITIONS`.
https://github.com/facebookresearch/XLM/blob/master/src/model/transformer.py#L19

**Comment by glample** [comment]
Can you run the same command, with `CUDA_LAUNCH_BLOCKING=1 python ...` instead? This should give a more accurate stack trace error.
Also, how long are your sentences? This looks like some kind of issue that you would get when you have sentences longer than `N_MAX_POSITIONS`.
https://github.com/facebookresearch/XLM/blob/master/src/model/transformer.py#L19

**Comment by JianLiu91** [comment]
> CUDA_LAUNCH_BLOCKING=1

I have run the same command with `CUDA_LAUNCH_BLOCKING=1`, and I get the output:

> INFO - 10/24/19 20:55:59 - 0:00:31 - Creating new training data iterator (bt,en) ...
INFO - 10/24/19 20:56:24 - 0:00:55 -       5 -   14.55 sent/s -   499.11 words/s - AE-en: 13.5713 || AE-fr: 14.0900 || BT-en-fr-en: 11.6178 || BT-fr-en-fr: 11.8031 -  - model LR: 5.9950e-07
INFO - 10/24/19 20:56:24 - 0:00:55 -       5 -   15.13 sent/s -   500.53 words/s - AE-en: 13.4894 || AE-fr: 13.9529 || BT-en-fr-en: 11.7121 || BT-fr-en-fr: 12.0392 -  - model LR: 5.9950e-07
INFO - 10/24/19 20:56:24 - 0:00:55 -       5 -   16.15 sent/s -   497.51 words/s - AE-en: 13.6386 || AE-fr: 14.0646 || BT-en-fr-en: 11.6182 || BT-fr-en-fr: 11.8317 -  - model LR: 5.9950e-07
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 288, in main
    trainer.bt_step(lang1, lang2, lang3, params.lambda_bt)
  File "/home/jliu/research/XLM/src/trainer.py", line 902, in bt_step
    x2, len2 = _decoder.generate(enc1, len1, lang2_id, max_len=int(1.3 * len1.max().item() + 5))
  File "/home/jliu/research/XLM/src/model/transformer.py", line 497, in generate
    cache=cache
  File "/home/jliu/research/XLM/src/model/transformer.py", line 326, in forward
    return self.fwd(**kwargs)
  File "/home/jliu/research/XLM/src/model/transformer.py", line 395, in fwd
    attn = self.attentions[i](tensor, attn_mask, cache=cache)
  File "/home/jliu/venv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jliu/research/XLM/src/model/transformer.py", line 211, in forward
    mask = (mask == 0).view(mask_reshape).expand_as(scores)               # (bs, n_heads, qlen, klen)
RuntimeError: CUDA error: an illegal memory access was encountered
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [81,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
...
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [87,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 288, in main
    trainer.bt_step(lang1, lang2, lang3, params.lambda_bt)
  File "/home/jliu/research/XLM/src/trainer.py", line 902, in bt_step
    x2, len2 = _decoder.generate(enc1, len1, lang2_id, max_len=int(1.3 * len1.max().item() + 5))
  File "/home/jliu/research/XLM/src/model/transformer.py", line 497, in generate
    cache=cache
  File "/home/jliu/research/XLM/src/model/transformer.py", line 326, in forward
    return self.fwd(**kwargs)
  File "/home/jliu/research/XLM/src/model/transformer.py", line 384, in fwd
    tensor = tensor + self.position_embeddings(positions).expand_as(tensor)
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f7ce6b97813 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x16126 (0x7f7ce6dd2126 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x16b11 (0x7f7ce6dd2b11 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7f7ce6b87f0d in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: c10d::Reducer::~Reducer() + 0x449 (0x7f7d32cf31b9 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: std::_Sp_counted_ptr<c10d::Reducer*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() + 0x12 (0x7f7d32cd1b62 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0x46 (0x7f7d32715de6 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x7a13db (0x7f7d32cd23db in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x20f120 (0x7f7d32740120 in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x2103ae (0x7f7d327413ae in /home/jliu/venv3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

**Comment by vsoto** [comment]
I'm pertaining a language model with MLM and TLM on english, french and spanish and I get this error constantly. I've filtered out every sentence and parallel sentence from the corpora that is longer or equal to 512 tokens, and I still get it. It always happens right after epoch = 0 is finished. This is the error trace:

SLURM job: True
0 - SLURM_JOB_ID: 1866815
0 - SLURM_JOB_NODELIST: t064
0 - SLURM_JOB_NUM_NODES: 1
0 - SLURM_NTASKS: 1
0 - SLURM_TASKS_PER_NODE: 1
0 - SLURM_MEM_PER_NODE: 153600
0 - SLURM_MEM_PER_CPU: None
0 - SLURM_NODEID: 0
0 - SLURM_PROCID: 0
0 - SLURM_LOCALID: 0
0 - SLURM_TASK_PID: 210754
0 - Master address: t064
0 - Master port   : -1
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : t064
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 295, in main
    scores = evaluator.run_all_evals(trainer)
  File "/moto/katt2/users/vs2411/XLM/src/evaluation/evaluator.py", line 236, in run_all_evals
    self.evaluate_mlm(scores, data_set, lang1, lang2)
  File "/moto/katt2/users/vs2411/XLM/src/evaluation/evaluator.py", line 375, in evaluate_mlm
    tensor = model('fwd', x=x, lengths=lengths, positions=positions, langs=langs, causal=False)
  File "/moto/home/vs2411/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/moto/katt2/users/vs2411/XLM/src/model/transformer.py", line 326, in forward
    return self.fwd(**kwargs)
  File "/moto/katt2/users/vs2411/XLM/src/model/transformer.py", line 384, in fwd
    tensor = tensor + self.position_embeddings(positions).expand_as(tensor)
RuntimeError: CUDA error: device-side assert triggered
