### ISSUE TITLE
I train UNMT with multi-GPU got the following errors!

### ISSUE THREAD

**Issue by JxuHenry** [facebookresearch/XLM#224]
**I used single GPU to train UNMT without any errors, but I used Multi-GPU to report the following errors:**
INFO - 10/28/19 12:58:00 - 0:00:17 - ============ Starting epoch 0 ... ============
INFO - 10/28/19 12:58:00 - 0:00:17 - Creating new training data iterator (ae,en) ...
INFO - 10/28/19 12:58:01 - 0:00:19 - ============ Starting epoch 0 ... ============
INFO - 10/28/19 12:58:01 - 0:00:19 - Creating new training data iterator (ae,fr) ...
INFO - 10/28/19 12:58:05 - 0:00:22 - Creating new training data iterator (ae,fr) ...
INFO - 10/28/19 12:58:05 - 0:00:22 - Creating new training data iterator (ae,en) ...
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 280, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/home/lty/UNMT/XLM-master/src/trainer.py", line 851, in mt_step
    enc1 = self.encoder('fwd', x=x1, lengths=len1, langs=langs1, causal=False)
  File "/opt/anaconda3-2019.7/envs/pt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3-2019.7/envs/pt/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 459, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /opt/conda/conda-bld/pytorch_1565272279342/work/torch/csrc/distributed/c10d/reducer.cpp:518)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fa0136f7e37 in /opt/anaconda3-2019.7/envs/pt/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x7b7 (0x7fa049b33497 in /opt/anaconda3-2019.7/envs/pt/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x699443 (0x7fa049b22443 in /opt/anaconda3-2019.7/envs/pt/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1c8316 (0x7fa049651316 in /opt/anaconda3-2019.7/envs/pt/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyCFunction_FastCallDict + 0x154 (0x564656528c54 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #5: <unknown function> + 0x199c0e (0x5646565b0c0e in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x30a (0x5646565d375a in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #7: <unknown function> + 0x192e66 (0x5646565a9e66 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #8: _PyFunction_FastCallDict + 0x3d8 (0x5646565ab598 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #9: _PyObject_FastCallDict + 0x26f (0x56465652901f in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #10: _PyObject_Call_Prepend + 0x63 (0x56465652daa3 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #11: PyObject_Call + 0x3e (0x564656528a5e in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x19e7 (0x5646565d4e37 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #13: <unknown function> + 0x192e66 (0x5646565a9e66 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #14: _PyFunction_FastCallDict + 0x3d8 (0x5646565ab598 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #15: _PyObject_FastCallDict + 0x26f (0x56465652901f in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #16: _PyObject_Call_Prepend + 0x63 (0x56465652daa3 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #17: PyObject_Call + 0x3e (0x564656528a5e in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #18: <unknown function> + 0x16b371 (0x564656582371 in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #19: _PyObject_FastCallDict + 0x8b (0x564656528e3b in /opt/anaconda3-2019.7/envs/pt/bin/python)
frame #20: _PyObject_FastCallKeywords + 0xaa (0x5646565ab18a in /opt/anaconda3-2019.7/envs/pt/bin/python)

**I started with the following script:**
export NGPU=4
export CUDA_VISIBLE_DEVICES=0,1,2,3

python -m torch.distributed.launch --nproc_per_node=$NGPU train.py \
       --exp_name unsupMT_enfr \
       --dump_path ./dumped/ \
       --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' \
       --data_path ./data/processed/en-fr/ \
       --lgs 'en-fr' \
       --ae_steps 'en,fr' \
       --bt_steps 'en-fr-en,fr-en-fr' \
       --word_shuffle 3 \
       --word_dropout 0.1 \
       --word_blank 0.1 \
       --lambda_ae '0:1,100000:0.1,300000:0' \
       --encoder_only false \
       --emb_dim 1024 \
       --n_layers 6 \
       --n_heads 8 \
       --dropout 0.1 \
       --attention_dropout 0.1 \
       --gelu_activation true \
       --tokens_per_batch 2000 \
       --batch_size 32 \
       --bptt 256 \
       --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
       --epoch_size 200000 \
       --eval_bleu true \
       --stopping_criterion 'valid_en-fr_mt_bleu,10' \
       --validation_metrics 'valid_en-fr_mt_bleu'

**Comment by JxuHenry** [comment]
Oh, Sorry, I didn't  attention to the issue [](https://github.com/facebookresearch/XLM/issues/211) it fix this issue!
