### ISSUE TITLE
How to reproduce UNMT en-de results?

### ISSUE THREAD

**Issue by lyy1994** [facebookresearch/XLM#243]
Hi, I am trying to reproduce the unsupervised en-de results. When I used the following command to run the code

    python3 -m torch.distributed.launch --nproc_per_node=8 
    train.py 
    --exp_name en-de 
    --exp_id '1' 
    --dump_path checkpoints/umt/torch-1.1.0 
    --reload_model 'mlm_ende_1024.pth,mlm_ende_1024.pth' 
    --data_path data-bin/wmt.en-de 
    --lgs 'en-de' 
    --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 
    --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true 
    --tokens_per_batch 2000 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 
    --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-de_mt_bleu,10' --validation_metrics 'valid_en-de_mt_bleu' --accumulate_gradients 1 
    --master_port 28979 --ae_steps 'en,de' 
    --lambda_ae '0:1,100000:0.1,300000:0' --bt_steps 'en-de-en,de-en-de' 
    --lambda_bt '1' 
    --fp16 true --amp 2

I encounter the following error:

    Traceback (most recent call last):
      File "/home/liyanyang/nmt-research/umt/train.py", line 350, in <module>
        main(params)
      File "/home/liyanyang/nmt-research/umt/train.py", line 244, in main
        data = load_data(params)
      File "/home/liyanyang/nmt-research/umt/src/data/loader.py", line 352, in load_data
        load_mono_data(params, data)
      File "/home/liyanyang/nmt-research/umt/src/data/loader.py", line 131, in load_mono_data
        data['mono_stream'][lang][splt] = StreamDataset(mono_data['sentences'], mono_data['positions'], bs, params)
      File "/home/liyanyang/nmt-research/umt/src/data/dataset.py", line 37, in __init__
        self.data = np.zeros((n_batches * bptt + 1, bs), dtype=sent.dtype) + self.eos
    MemoryError

Does my machine not have enough RAM to load all the dataset? It has 220G RAM with 8 Titan V GPU. If so, how can I reduce the memory usage so as to reproduce the result?

**Comment by stoicboyoversea** [comment]
Try with --tokens_per_batch 1000.

**Comment by lyy1994** [comment]
> Try with --tokens_per_batch 1000.

I think this is not the GPU memory but instead the RAM problem.

**Comment by liesun1994** [comment]
> > Try with --tokens_per_batch 1000.
> 
> I think this is not the GPU memory but instead the RAM problem, because the same setting can be run on smaller datasets.

Have you solved this problem ?

**Comment by lyy1994** [comment]
> > > Try with --tokens_per_batch 1000.
> > 
> > 
> > I think this is not the GPU memory but instead the RAM problem, because the same setting can be run on smaller datasets.
> 
> Have you solved this problem ?

Unfortunately, no.
