### ISSUE TITLE
Multi-GPU code not working for UNMT en-fr experiment

### ISSUE THREAD

**Issue by Akella17** [facebookresearch/XLM#257]
@aconneau @glample I cloned this repository and followed the instructions for running the UNMT experiment. While the single GPU code works, the execution of Multi-GPU code terminates with the below-mentioned error.

While this issue has been highlighted previously, making those suggested changes did not work in my case. More specifically, the changes I made are:
1) src/trainer.py: find_unused_parameters=True in nn.parallel.DistributedDataParallel
2) src/model/__init__.py: encoder = TransformerModel(params, dico, is_encoder=True, with_output=False)
3) src/model/__init__.py: encoder.load_state_dict(enc_reload, strict=False)

I am using the PyTorch 1.1.0 version. Can someone mention a way to fix this issue?

```
INFO - 01/04/20 09:55:54 - 0:00:19 - ============ Starting epoch 0 ... ============
INFO - 01/04/20 09:55:54 - 0:00:19 - Creating new training data iterator (ae,en) ...
INFO - 01/04/20 09:55:54 - 0:00:19 - Optimizers: model
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 280, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/home1/sukanta/Ravitej/LatestXLM/src/trainer.py", line 858, in mt_step
    _, loss = self.decoder('predict', tensor=dec2, pred_mask=pred_mask, y=y, get_scores=False)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 390, in forward
    self.reducer.prepare_for_backward(list(_find_tensors(output)))
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:408)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fb54f064441 in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fb54f063d7a in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x5ec (0x7fb58eb3883c in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x6c52bd (0x7fb58eb2e2bd in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x130cfc (0x7fb58e599cfc in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyCFunction_FastCallDict + 0x154 (0x558f5ac0d744 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #6: <unknown function> + 0x19857e (0x558f5ac9457e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x30a (0x558f5acb938a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #8: <unknown function> + 0x1918e4 (0x558f5ac8d8e4 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #9: _PyFunction_FastCallDict + 0x3da (0x558f5ac8ee6a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #10: _PyObject_FastCallDict + 0x26f (0x558f5ac0db0f in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #11: _PyObject_Call_Prepend + 0x63 (0x558f5ac126a3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #12: PyObject_Call + 0x3e (0x558f5ac0d54e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #13: _PyEval_EvalFrameDefault + 0x19ec (0x558f5acbaa6c in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #14: <unknown function> + 0x1918e4 (0x558f5ac8d8e4 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #15: _PyFunction_FastCallDict + 0x3da (0x558f5ac8ee6a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #16: _PyObject_FastCallDict + 0x26f (0x558f5ac0db0f in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #17: _PyObject_Call_Prepend + 0x63 (0x558f5ac126a3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #18: PyObject_Call + 0x3e (0x558f5ac0d54e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #19: <unknown function> + 0x16ba91 (0x558f5ac67a91 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #20: _PyObject_FastCallDict + 0x8b (0x558f5ac0d92b in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #21: _PyObject_FastCallKeywords + 0xaa (0x558f5ac8ea5a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #22: <unknown function> + 0x19857e (0x558f5ac9457e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x10c7 (0x558f5acba147 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #24: <unknown function> + 0x19253b (0x558f5ac8e53b in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #25: <unknown function> + 0x198505 (0x558f5ac94505 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x30a (0x558f5acb938a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #27: <unknown function> + 0x19253b (0x558f5ac8e53b in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #28: <unknown function> + 0x198505 (0x558f5ac94505 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x30a (0x558f5acb938a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #30: PyEval_EvalCodeEx + 0x329 (0x558f5ac8f289 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #31: PyEval_EvalCode + 0x1c (0x558f5ac9001c in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #32: <unknown function> + 0x2163c4 (0x558f5ad123c4 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #33: PyRun_FileExFlags + 0xa1 (0x558f5ad127c1 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #34: PyRun_SimpleFileExFlags + 0x1c3 (0x558f5ad129c3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #35: Py_Main + 0x613 (0x558f5ad164b3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #36: main + 0xee (0x558f5abdf02e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #37: __libc_start_main + 0xf0 (0x7fb59c641830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #38: <unknown function> + 0x1c3e0e (0x558f5acbfe0e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)

INFO - 01/04/20 09:55:56 - 0:00:21 - ============ Starting epoch 0 ... ============
INFO - 01/04/20 09:55:56 - 0:00:21 - Creating new training data iterator (ae,fr) ...
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 280, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/home1/sukanta/Ravitej/LatestXLM/src/trainer.py", line 858, in mt_step
    _, loss = self.decoder('predict', tensor=dec2, pred_mask=pred_mask, y=y, get_scores=False)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 390, in forward
    self.reducer.prepare_for_backward(list(_find_tensors(output)))
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:408)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f40e2c88441 in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f40e2c87d7a in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x5ec (0x7f412275c83c in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x6c52bd (0x7f41227522bd in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x130cfc (0x7f41221bdcfc in /home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyCFunction_FastCallDict + 0x154 (0x55c4785af744 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #6: <unknown function> + 0x19857e (0x55c47863657e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x30a (0x55c47865b38a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #8: <unknown function> + 0x1918e4 (0x55c47862f8e4 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #9: _PyFunction_FastCallDict + 0x3da (0x55c478630e6a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #10: _PyObject_FastCallDict + 0x26f (0x55c4785afb0f in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #11: _PyObject_Call_Prepend + 0x63 (0x55c4785b46a3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #12: PyObject_Call + 0x3e (0x55c4785af54e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #13: _PyEval_EvalFrameDefault + 0x19ec (0x55c47865ca6c in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #14: <unknown function> + 0x1918e4 (0x55c47862f8e4 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #15: _PyFunction_FastCallDict + 0x3da (0x55c478630e6a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #16: _PyObject_FastCallDict + 0x26f (0x55c4785afb0f in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #17: _PyObject_Call_Prepend + 0x63 (0x55c4785b46a3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #18: PyObject_Call + 0x3e (0x55c4785af54e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #19: <unknown function> + 0x16ba91 (0x55c478609a91 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #20: _PyObject_FastCallDict + 0x8b (0x55c4785af92b in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #21: _PyObject_FastCallKeywords + 0xaa (0x55c478630a5a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #22: <unknown function> + 0x19857e (0x55c47863657e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x10c7 (0x55c47865c147 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #24: <unknown function> + 0x19253b (0x55c47863053b in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #25: <unknown function> + 0x198505 (0x55c478636505 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x30a (0x55c47865b38a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #27: <unknown function> + 0x19253b (0x55c47863053b in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #28: <unknown function> + 0x198505 (0x55c478636505 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x30a (0x55c47865b38a in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #30: PyEval_EvalCodeEx + 0x329 (0x55c478631289 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #31: PyEval_EvalCode + 0x1c (0x55c47863201c in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #32: <unknown function> + 0x2163c4 (0x55c4786b43c4 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #33: PyRun_FileExFlags + 0xa1 (0x55c4786b47c1 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #34: PyRun_SimpleFileExFlags + 0x1c3 (0x55c4786b49c3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #35: Py_Main + 0x613 (0x55c4786b84b3 in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #36: main + 0xee (0x55c47858102e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)
frame #37: __libc_start_main + 0xf0 (0x7f4130265830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #38: <unknown function> + 0x1c3e0e (0x55c478661e0e in /home1/sukanta/anaconda3/envs/UNMT/bin/python)

Traceback (most recent call last):
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home1/sukanta/anaconda3/envs/UNMT/bin/python', '-u', 'train.py', '--local_rank=0', '--exp_name', 'unsupMT_enfr', '--dump_path', './dumped/', '--reload_model', 'mlm_enfr_1024.pth,mlm_enfr_1024.pth', '--data_path', './data/processed/en-fr/', '--lgs', 'en-fr', '--ae_steps', 'en,fr', '--bt_steps', 'en-fr-en,fr-en-fr', '--word_shuffle', '3', '--word_dropout', '0.1', '--word_blank', '0.1', '--lambda_ae', '0:1,100000:0.1,300000:0', '--encoder_only', 'false', '--emb_dim', '1024', '--n_layers', '6', '--n_heads', '8', '--dropout', '0.1', '--attention_dropout', '0.1', '--gelu_activation', 'true', '--tokens_per_batch', '1000', '--batch_size', '32', '--bptt', '256', '--optimizer', 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001', '--epoch_size', '200000', '--eval_bleu', 'true', '--stopping_criterion', 'valid_en-fr_mt_bleu,10', '--validation_metrics', 'valid_en-fr_mt_bleu']' returned non-zero exit status 1.
```

**Comment by jude-nlp** [comment]
Hi,
I got the same problem,  did you solve the problem? 
Thank you.

**Comment by renziver** [comment]
@Akella17 @jude-nlp try following the fix in issue #211

**Comment by fallcat** [comment]
@renziver @jude-nlp Did you fix the issue? I tried the fix in #211 but it still gives an error:
`Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
`

**Comment by jiahaosuda** [comment]
@renziver @fallcat @jude-nlp @Akella17 Hi, did you fix the issue? I tried the fix in [#211](https://github.com/facebookresearch/XLM/issues/211), but it still doesn't work and the error doesn't change.

**Comment by fallcat** [comment]
@jiahaosuda I added the flag `--debug_slurm true` and it worked.

**Comment by fallcat** [comment]
@jiahaosuda this is my script (sbatch with 8 GPUs):

> export NGPU=8; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py \
  --exp_name unsupMT_deen \
  --dump_path ./dumped \
  --reload_model 'dumped/deen_mlm/6771308/best-valid_mlm_ppl.pth,dumped/deen_mlm/6771308/best-valid_mlm_ppl.pth' \
  --data_path ./data/processed/de-en/ \
  --lgs 'de-en'   \   
  --ae_steps 'de,en'  \
  --bt_steps 'de-en-de,en-de-en' \
  --word_shuffle 3   \   
  --word_dropout 0.1  \
  --word_blank 0.1  \
  --lambda_ae '0:1,100000:0.1,300000:0' \
  --encoder_only false \
  --emb_dim 1024  \
  --n_layers 6  \
  --n_heads 8   \   
  --dropout 0.1   \   
  --attention_dropout 0.1 \
  --gelu_activation true  \
  --fp16 true \
  --amp 1 \ 
  --accumulate_gradients 2 \ 
  --tokens_per_batch 1000   \   
  --batch_size 32  \
  --bptt 256 \
  --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001  \
  --epoch_size 200000  \
  --eval_bleu true  \
  --stopping_criterion 'valid_de-en_mt_bleu,10'  \
  --validation_metrics 'valid_de-en_mt_bleu' \
  --debug_slurm true

**Comment by jiahaosuda** [comment]
> @jiahaosuda this is my script (sbatch with 8 GPUs):
> 
> > export NGPU=8; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py 
> >   --exp_name unsupMT_deen 
> >   --dump_path ./dumped 
> >   --reload_model 'dumped/deen_mlm/6771308/best-valid_mlm_ppl.pth,dumped/deen_mlm/6771308/best-valid_mlm_ppl.pth' 
> >   --data_path ./data/processed/de-en/ 
> >   --lgs 'de-en'   \
> > --ae_steps 'de,en'  
> >   --bt_steps 'de-en-de,en-de-en' 
> >   --word_shuffle 3   \
> > --word_dropout 0.1  
> >   --word_blank 0.1  
> >   --lambda_ae '0:1,100000:0.1,300000:0' 
> >   --encoder_only false 
> >   --emb_dim 1024  
> >   --n_layers 6  
> >   --n_heads 8   \
> > --dropout 0.1   \
> > --attention_dropout 0.1 
> >   --gelu_activation true  
> >   --fp16 true 
> >   --amp 1 \
> > --accumulate_gradients 2 \
> > --tokens_per_batch 1000   \
> > --batch_size 32  
> >   --bptt 256 
> >   --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001  
> >   --epoch_size 200000  
> >   --eval_bleu true  
> >   --stopping_criterion 'valid_de-en_mt_bleu,10'  
> >   --validation_metrics 'valid_de-en_mt_bleu' 
> >   --debug_slurm true

Sorry for late reply. My code works well now. The error exists just because i use the code of `torch0.4` version in the environment of `torch1.0`. When I run the code in the environment of `torch0.4`, it's just ok.
