### ISSUE TITLE
Problem in Running translate.py file

### ISSUE THREAD

**Issue by RavneetDTU** [facebookresearch/XLM#268]
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main(params)
  File "translate.py", line 77, in main
    encoder.load_state_dict(reloaded['encoder'])
KeyError: 'encoder'

**Comment by danielcamara** [comment]
Hi 

We have the same problem! Did you find the answer?

Best regards....

Daniel

**Comment by arjunkoneru** [comment]
You can try the code mentioned in #273 . Hope it works!
