### ISSUE TITLE
running translate.py

### ISSUE THREAD

**Issue by danielcamara** [facebookresearch/XLM#273]
Hi, really nice work, nice paper. 

I am sorry, but any would like just to play a little with the provided trained models. Any one managed to run translate.py with these models for translation?  
For example, https://dl.fbaipublicfiles.com/XLM/mlm_100_1280.pth one? 
I tried to run as it is suggested on the header of the translate.py, but it didn't work at all. It seems that either the code has a problem, or the model is missing something. 

cat text.txt | python translate.py --exp_name test --exp_id test_id --model_path models/mlm_100_1280.pth --output_path test_out --src_lang pt --tgt_lang en

I got this: 
```
INFO - 03/03/20 23:25:28 - 0:00:03 - Supported languages: af, als, am, an, ang, ar, arz, ast, az, bar, be, bg, bn, br, bs, ca, ceb, ckb, cs, cy, da, de, el, en, eo, es, et, eu, fa, fi, fr, fy, ga, gan, gl, gu, he, hi, hr, hu, hy, ia, id, is, it, ja, jv, ka, kk, kn, ko, ku, la, lb, lt, lv, mk, ml, mn, mr, ms, my, nds, ne, nl, nn, no, oc, pl, pt, ro, ru, scn, sco, sh, si, simple, sk, sl, sq, sr, sv, sw, ta, te, th, tl, tr, tt, uk, ur, uz, vi, war, wuu, yi, zh, zh_classical, zh_min_nan, zh_yue
Traceback (most recent call last):
  File "/home/daniel/PycharmProjects/XLM-master/translate.py", line 142, in <module>
    main(params)
  File "/home/daniel/PycharmProjects/XLM-master/translate.py", line 77, in main
    encoder.load_state_dict(reloaded['encoder'])
KeyError: 'encoder'
```
looking into the code it seems that reloaded does not have the entries encoder/decoder. It has an entry model, that is used on the tutorial. However, if we change the reload["encoder"] to reload["model"], idem for the decoder, the error changes, and then is on the load state of the decoder that seems to miss layers on the model... I don't know.

This is why I am asking if anyone managed to run with the provided models or not! 

Best regards...
-- Daniel

**Comment by fallcat** [comment]
I haven't run the translate.py yet but will be trying that soon. I feel that you need to train an MT model first? Isn't the pretrained model just a masked language model?

**Comment by arjunkoneru** [comment]
Maybe try using reload["model"] and after that change the line to this which will solve the missing parameters it didn't have while pretraining
`decoder.load_state_dict(reloaded['decoder'],strict=False)`

**Comment by arjunkoneru** [comment]
You can replace line 77-78 in translate.py with the following piece of code. This issue is explained here in  #https://github.com/facebookresearch/XLM/issues/65 
```
enc_reload = reloaded['model' if 'model' in reloaded else 'encoder']
    if all([k.startswith('module.') for k in enc_reload.keys()]):
        enc_reload = {k[len('module.'):]: v for k, v in enc_reload.items()}
    encoder.load_state_dict(enc_reload)
    #encoder.load_state_dict(reloaded['encoder'])
    dec_reload = reloaded['model' if 'model' in reloaded else 'decoder']
    if all([k.startswith('module.') for k in dec_reload.keys()]):
        dec_reload = {k[len('module.'):]: v for k, v in dec_reload.items()}
    decoder.load_state_dict(dec_reload)
    #decoder.load_state_dict(reloaded['decoder'])
```

**Comment by Timothy199707** [comment]
I tried the solution above, but got this error instead (not that I'm also using https://dl.fbaipublicfiles.com/XLM/mlm_100_1280.pth)

decoder.load_state_dict(dec_reload)
  File "/home/timo/.conda/envs/NER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Missing key(s) in state_dict: "layer_norm15.0.weight", "layer_norm15.0.bias", "layer_norm15.1.weight", "layer_norm15.1.bias", "layer_norm15.2.weight", "layer_norm15.2.bias", "layer_norm15.3.weight", "layer_norm15.3.bias", "layer_norm15.4.weight", "layer_norm15.4.bias", "layer_norm15.5.weight", "layer_norm15.5.bias", "layer_norm15.6.weight", "layer_norm15.6.bias", "layer_norm15.7.weight", "layer_norm15.7.bias", "layer_norm15.8.weight", "layer_norm15.8.bias", "layer_norm15.9.weight", "layer_norm15.9.bias", "layer_norm15.10.weight", "layer_norm15.10.bias", "layer_norm15.11.weight", "layer_norm15.11.bias", "layer_norm15.12.weight", "layer_norm15.12.bias", "layer_norm15.13.weight", "layer_norm15.13.bias", "layer_norm15.14.weight", "layer_norm15.14.bias", "layer_norm15.15.weight", "layer_norm15.15.bias", "encoder_attn.0.q_lin.weight", "encoder_attn.0.q_lin.bias", "encoder_attn.0.k_lin.weight", "encoder_attn.0.k_lin.bias", "encoder_attn.0.v_lin.weight", "encoder_attn.0.v_lin.bias", "encoder_attn.0.out_lin.weight", "encoder_attn.0.out_lin.bias", "encoder_attn.1.q_lin.weight", "encoder_attn.1.q_lin.bias", "encoder_attn.1.k_lin.weight", "encoder_attn.1.k_lin.bias", "encoder_attn.1.v_lin.weight", "encoder_attn.1.v_lin.bias", "encoder_attn.1.out_lin.weight", "encoder_attn.1.out_lin.bias", "encoder_attn.2.q_lin.weight", "encoder_attn.2.q_lin.bias", "encoder_attn.2.k_lin.weight", "encoder_attn.2.k_lin.bias", "encoder_attn.2.v_lin.weight", "encoder_attn.2.v_lin.bias", "encoder_attn.2.out_lin.weight", "encoder_attn.2.out_lin.bias", "encoder_attn.3.q_lin.weight", "encoder_attn.3.q_lin.bias", "encoder_attn.3.k_lin.weight", "encoder_attn.3.k_lin.bias", "encoder_attn.3.v_lin.weight", "encoder_attn.3.v_lin.bias", "encoder_attn.3.out_lin.weight", "encoder_attn.3.out_lin.bias", "encoder_attn.4.q_lin.weight", "encoder_attn.4.q_lin.bias", "encoder_attn.4.k_lin.weight", "encoder_attn.4.k_lin.bias", "encoder_attn.4.v_lin.weight", "encoder_attn.4.v_lin.bias", "encoder_attn.4.out_lin.weight", "encoder_attn.4.out_lin.bias", "encoder_attn.5.q_lin.weight", "encoder_attn.5.q_lin.bias", "encoder_attn.5.k_lin.weight", "encoder_attn.5.k_lin.bias", "encoder_attn.5.v_lin.weight", "encoder_attn.5.v_lin.bias", "encoder_attn.5.out_lin.weight", "encoder_attn.5.out_lin.bias", "encoder_attn.6.q_lin.weight", "encoder_attn.6.q_lin.bias", "encoder_attn.6.k_lin.weight", "encoder_attn.6.k_lin.bias", "encoder_attn.6.v_lin.weight", "encoder_attn.6.v_lin.bias", "encoder_attn.6.out_lin.weight", "encoder_attn.6.out_lin.bias", "encoder_attn.7.q_lin.weight", "encoder_attn.7.q_lin.bias", "encoder_attn.7.k_lin.weight", "encoder_attn.7.k_lin.bias", "encoder_attn.7.v_lin.weight", "encoder_attn.7.v_lin.bias", "encoder_attn.7.out_lin.weight", "encoder_attn.7.out_lin.bias", "encoder_attn.8.q_lin.weight", "encoder_attn.8.q_lin.bias", "encoder_attn.8.k_lin.weight", "encoder_attn.8.k_lin.bias", "encoder_attn.8.v_lin.weight", "encoder_attn.8.v_lin.bias", "encoder_attn.8.out_lin.weight", "encoder_attn.8.out_lin.bias", "encoder_attn.9.q_lin.weight", "encoder_attn.9.q_lin.bias", "encoder_attn.9.k_lin.weight", "encoder_attn.9.k_lin.bias", "encoder_attn.9.v_lin.weight", "encoder_attn.9.v_lin.bias", "encoder_attn.9.out_lin.weight", "encoder_attn.9.out_lin.bias", "encoder_attn.10.q_lin.weight", "encoder_attn.10.q_lin.bias", "encoder_attn.10.k_lin.weight", "encoder_attn.10.k_lin.bias", "encoder_attn.10.v_lin.weight", "encoder_attn.10.v_lin.bias", "encoder_attn.10.out_lin.weight", "encoder_attn.10.out_lin.bias", "encoder_attn.11.q_lin.weight", "encoder_attn.11.q_lin.bias", "encoder_attn.11.k_lin.weight", "encoder_attn.11.k_lin.bias", "encoder_attn.11.v_lin.weight", "encoder_attn.11.v_lin.bias", "encoder_attn.11.out_lin.weight", "encoder_attn.11.out_lin.bias", "encoder_attn.12.q_lin.weight", "encoder_attn.12.q_lin.bias", "encoder_attn.12.k_lin.weight", "encoder_attn.12.k_lin.bias", "encoder_attn.12.v_lin.weight", "encoder_attn.12.v_lin.bias", "encoder_attn.12.out_lin.weight", "encoder_attn.12.out_lin.bias", "encoder_attn.13.q_lin.weight", "encoder_attn.13.q_lin.bias", "encoder_attn.13.k_lin.weight", "encoder_attn.13.k_lin.bias", "encoder_attn.13.v_lin.weight", "encoder_attn.13.v_lin.bias", "encoder_attn.13.out_lin.weight", "encoder_attn.13.out_lin.bias", "encoder_attn.14.q_lin.weight", "encoder_attn.14.q_lin.bias", "encoder_attn.14.k_lin.weight", "encoder_attn.14.k_lin.bias", "encoder_attn.14.v_lin.weight", "encoder_attn.14.v_lin.bias", "encoder_attn.14.out_lin.weight", "encoder_attn.14.out_lin.bias", "encoder_attn.15.q_lin.weight", "encoder_attn.15.q_lin.bias", "encoder_attn.15.k_lin.weight", "encoder_attn.15.k_lin.bias", "encoder_attn.15.v_lin.weight", "encoder_attn.15.v_lin.bias", "encoder_attn.15.out_lin.weight", "encoder_attn.15.out_lin.bias".

**Comment by arjunkoneru** [comment]
Can you try adding strict=false as an argument 
decoder.load_state_dict(dec_reload, strict = False)

**Comment by Timothy199707** [comment]
Thank you for the quick reply,
The model was successfully loaded, but the translation result is ... strange,
Here is one of my translation output:
м@@ м@@ м@@ м@@ м@@ м@@ м@@ м@@ м@@ м@@ м@@ м@@

I think I'm just loading parameters from the encoder to the decoder? Or maybe I'm just doing something wrong.

**Comment by arjunkoneru** [comment]
When pretraining with MLM task you only use the encoder. so, when you reload it in the decoder the source attention parameters aren't there before which raises the error and using strict solves the issue. Can you check the hypothesis and reference files in your experiment under the hypothesis folder?

**Comment by Timothy199707** [comment]
I see, maybe I should use mlm_tlm_xnli15_1024.pth instead (which has tlm pretraining)?

**Comment by Anwarvic** [comment]
@Timothy199707, I think XNLI models are for classification. Check issue #78
