### ISSUE TITLE
Error while fine tuning XLM 100 for Cross lingual Text Classification

### ISSUE THREAD

**Issue by DebanjanaKar** [facebookresearch/XLM#275]
Hi! Thank you for this repository where everything is so well explained. Congratulations on such awesome work. I'm trying to fine-tune the XLM-100 model on the STS-B task for Cross-lingual text classification application. I have downloaded the pre-trained model from https://dl.fbaipublicfiles.com/XLM/mlm_100_1280.pth 
I downloaded Glue data and preprocessed it using ./get-data-glue.sh and ./prepare-glue.sh respectively. While running the fine-tuning command, I get an Assertion Error which says that it can't find the valid.s1.pth file. 
```
Traceback (most recent call last):
  File "glue-xnli.py", line 114, in <module>
    glue.run(task)
  File "/mnt/d/codes/fine_tune_xlm/master/XLM-master/src/evaluation/glue.py", line 80, in run
    self.data = self.load_data(task)
  File "/mnt/d/codes/fine_tune_xlm/master/XLM-master/src/evaluation/glue.py", line 275, in load_data
    data1 = load_binarized(os.path.join(dpath, '%s.s1.pth' % splt), params)
  File "/mnt/d/codes/fine_tune_xlm/master/XLM-master/src/data/loader.py", line 66, in load_binarized
    assert os.path.isfile(path), path
AssertionError: ./data/processed/XLM_en/eval/STS-B/valid.s1.pth
```
 Since there are no valid files in the glue preprocessed folder but dev files, I tried to rename the dev files as valid but that raises another Assertion Exception which says this : 
```
Traceback (most recent call last):
  File "glue-xnli.py", line 114, in <module>
    glue.run(task)
  File "/mnt/d/codes/fine_tune_xlm/master/XLM-master/src/evaluation/glue.py", line 84, in run
    "and the same values for max_vocab and min_count.") % (len(self.data['dico']), len(self._embedder.dico)))
Exception: Dictionary in evaluation data (30145 words) seems different than the one in the pretrained model (200000 words). Please verify you used the same dictionary, and the same values for max_vocab and min_count.
```
@aconneau , @glample : Can any of you please guide me as to what might be the issue here? That would be really helpful.

**Comment by AnnaBanana92** [comment]
@DebanjanaKar Did you modify the path of BPE codes and vocab in the prepare-glue.sh script to match the XLM-100 model? It's hard-coded in the script to use the XLM_en.

**Comment by LetsGoFir** [comment]
Same error. What should it be if we do use the XLM_en?



> @DebanjanaKar Did you modify the path of BPE codes and vocab in the prepare-glue.sh script to match the XLM-100 model? It's hard-coded in the script to use the XLM_en.
