### ISSUE TITLE
How to reload 'best-valid_de-en_mt_bleu.pth'

### ISSUE THREAD

**Issue by jude-xg** [facebookresearch/XLM#282]
WARNING - 03/30/20 17:12:12 - 0:00:14 - Reloading checkpoint from /home/zxg/XLM/dumped/old-dev/supMT_fren_pretrain_nofreeze/iap4d21fkk/best-valid_de-en_mt_bleu.pth ...
WARNING - 03/30/20 17:12:13 - 0:00:15 - Not reloading checkpoint optimizer model.
WARNING - 03/30/20 17:12:13 - 0:00:15 - Reloading 'num_updates' and 'lr' for optimizer model.
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    main(params)
  File "train.py", line 244, in main
    trainer = EncDecTrainer(encoder, decoder, data, params)
  File "/home/zxg/XLM/src/trainer.py", line 814, in __init__
    super().__init__(data, params)
  File "/home/zxg/XLM/src/trainer.py", line 129, in __init__
    self.reload_checkpoint()
  File "/home/zxg/XLM/src/trainer.py", line 556, in reload_checkpoint
    param_group['num_updates'] = data[f'{name}_optimizer']['param_groups'][group_id]['num_updates']
KeyError: 'model_optimizer'

**Comment by liguo-cs** [comment]
I'd like to ask how do you solve this problem?
