### ISSUE TITLE
Problem in loading parallel data for supervised nmt fine tuning task

### ISSUE THREAD

**Issue by renziver** [facebookresearch/XLM#296]
I'm having problems in loading the datasets for fine tuning a pre-trained MLM for a supervised task. I properly ran the parallel corpus on the same preprocessing steps I did for the pretraining task (BPE, Binarization) but i'm having trouble in loading the data as I am encountering the following issue:

`INFO - 06/08/20 15:56:15 - 0:00:00 - ============ Parallel data (en-fil) 
INFO - 06/08/20 15:56:15 - 0:00:00 - Loading data from data/parallel/final/train.en-fil.en.pth ...
INFO - 06/08/20 15:56:17 - 0:00:03 - 898844080 words (1832 unique) in 1696536 sentences. 0 unknown words (0 unique) cov
ering 0.00% of the data.
INFO - 06/08/20 15:56:17 - 0:00:03 - Loading data from data/parallel/final/train.en-fil.fil.pth ...
INFO - 06/08/20 15:56:20 - 0:00:06 - 1054780346 words (1750 unique) in 1696536 sentences. 0 unknown words (0 unique) co
vering 0.00% of the data.
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 230, in main
    data = load_data(params)
  File "/home/renz_baliber_senti_com_ph/XLM/src/data/loader.py", line 337, in load_data
    load_para_data(params, data)
  File "/home/renz_baliber_senti_com_ph/XLM/src/data/loader.py", line 197, in load_para_data
    set_dico_parameters(params, data, tgt_data['dico'])
  File "/home/renz_baliber_senti_com_ph/XLM/src/data/loader.py", line 78, in set_dico_parameters
    assert data['dico'] == dico
AssertionError`

the directory structure of my data is as follow:
data/parallel/final

├── train.en
├── train.en-fil.en.pth
├── train.fil
├── train.en-fil.fil.pth
├── valid.en
├── valid-en-fil.en.pth
├── valid.fil
├── valid.en-fil.fil.pth
├── test.en
├── test.en-fil.en.pth
├── test.fil
├── test.en-fil.fil.pth
├── voab.en
├── vocab.fil
├── vocab.en-fil

as opposed to the issue raised in #293 , i'm sure that I am pointing to the correct data path.
training snippet:
`
LMPATH=dumped/xlm_fil_lm/zy3w4vrbeb
python train.py 
        --exp_name fil2en-nmt 
        --dump_path dumped/nmt 
        --reload_model $LMPATH/best-valid_mlm_ppl.pth,$LMPATH/best-valid_mlm_ppl.pth 
        --data_path data/parallel/final/ 
        --lgs 'en-fil' 
        --mt_step 'en-fil' 
        --encoder_only false 
        --emb_dim 512 
        --n_layers 6 
        --n_heads 8 
        --dropout 0.1 
        --attention_dropout 0.1 
        --gelu_activation true 
        --tokens_per_batch 2000 
        --batch_size 32 
        --bptt 256 
        --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 
        --epoch_size 20000 
        --eval_bleu true 
        --stopping_criterion valid_en-fil_mt_bleu,10 
        --validation_metrics valid_en-fil_mt_bleu`

**Comment by renziver** [comment]
Resolved the issue, I used a different vocab for the tgt and src data. should have used a shared vocab.
