### ISSUE TITLE
lang_embeddings.weight vector size mismatch when trying to use pretrained XLM for inference on unsupervised MT

### ISSUE THREAD

**Issue by meeps123** [facebookresearch/XLM#309]
Hello! I'm trying to use the 15 languages XLM trained on the MLM and TLM objective for transfer learning.

I'm tasked with performing unsupervised MT to translate traditional Chinese to English. 

I've implemented the steps in #200, namely:
* limiting vocab size using `--max_vocab 95000`
* in `src/model/__init__.py`, add `strict=False` to `encoder.load_state_dict(enc_reload)`

However, I am still getting a vector size mismatch error as follows:
```
Traceback (most recent call last):
  File "XLM/train.py", line 327, in <module>
    main(params)
  File "XLM/train.py", line 236, in main
    encoder, decoder = build_model(params, data['dico'])
  File "/content/XLM/src/model/__init__.py", line 164, in build_model
    encoder.load_state_dict(enc_reload, strict=False)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	size mismatch for lang_embeddings.weight: copying a param with shape torch.Size([15, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
```

This is my train command:

```
!python -W ignore XLM/train.py \
--exp_name unsupervisedMT_zhen_inf \
--dump_path ./dumped/ \
--reload_model mlm_tlm_xnli15_1024.pth, mlm_tlm_xnli15_1024.pth \
--data_path ./data/ \
--lgs 'zh-en' \
--ae_steps 'zh,en' \
--bt_steps 'zh-en-zh,en-zh-en' \
--word_shuffle 3 \
--word_dropout 0.1 \
--word_blank 0.1 \
--lambda_ae '0:1,100000:0.1,300000:0' \
--encoder_only false \
--emb_dim 1024 \
--n_layers 6 \
--n_heads 8 \
--dropout 0.1 \
--attention_dropout 0.1 \
--gelu_activation true \
--tokens_per_batch 2000 \
--batch_size 32 \
--bptt 256 \
--optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
--epoch_size 20000 \
--eval_bleu true \
--stopping_criterion 'valid_zh-en_mt_bleu,10' \
--validation_metrics 'valid_zh-en_mt_bleu' \
--max_vocab 95000
```

Any ideas? Thanks!!

@glample  @aconneau

**Comment by alloystory** [comment]
hi, did you manage to solve this issue? i am also facing the same issue

my guess is that the `--lgs` flag take into account the languages that the pretrained model is trained on. i tried changing `--lgs zh-en` to `--lgs 'ar-bg-de-el-en-es-fr-hi-ru-sw-th-tr-ur-vi-zh'` according to the https://github.com/facebookresearch/XLM#pretrain-a-language-model-with-mlm-and-tlm. after doing so, i didn't get the size mismatch error anymore, but i got an error with unexpected keys in state_dict

this is the error that i got
```
RuntimeError: Error(s) in loading state_dict for TransformerModel:
        Unexpected key(s) in state_dict: "attentions.6.q_lin.weight", "attentions.6.q_lin.bias", "attentions.6.k_lin.weight", "attentions.6.k_lin.bias", "attentions.6.v_lin.weight", "attentions.6.v_lin.bias", "attentions.6.out_lin.weight", "attentions.6.out_lin.bias", "attentions.7.q_lin.weight", "attentions.7.q_lin.bias", "attentions.7.k_lin.weight", "attentions.7.k_lin.bias", "attentions.7.v_lin.weight", "attentions.7.v_lin.bias", "attentions.7.out_lin.weight", "attentions.7.out_lin.bias", "attentions.8.q_lin.weight", "attentions.8.q_lin.bias", "attentions.8.k_lin.weight", "attentions.8.k_lin.bias", "attentions.8.v_lin.weight", "attentions.8.v_lin.bias", "attentions.8.out_lin.weight", "attentions.8.out_lin.bias", "attentions.9.q_lin.weight", "attentions.9.q_lin.bias", "attentions.9.k_lin.weight", "attentions.9.k_lin.bias", "attentions.9.v_lin.weight", "attentions.9.v_lin.bias", "attentions.9.out_lin.weight", "attentions.9.out_lin.bias", "attentions.10.q_lin.weight", "attentions.10.q_lin.bias", "attentions.10.k_lin.weight", "attentions.10.k_lin.bias", "attentions.10.v_lin.weight", "attentions.10.v_lin.bias", "attentions.10.out_lin.weight", "attentions.10.out_lin.bias", "attentions.11.q_lin.weight", "attentions.11.q_lin.bias", "attentions.11.k_lin.weight", "attentions.11.k_lin.bias", "attentions.11.v_lin.weight", "attentions.11.v_lin.bias", "attentions.11.out_lin.weight", "attentions.11.out_lin.bias", "layer_norm1.6.weight", "layer_norm1.6.bias", "layer_norm1.7.weight", "layer_norm1.7.bias", "layer_norm1.8.weight", "layer_norm1.8.bias", "layer_norm1.9.weight", "layer_norm1.9.bias", "layer_norm1.10.weight", "layer_norm1.10.bias", "layer_norm1.11.weight", "layer_norm1.11.bias", "ffns.6.lin1.weight", "ffns.6.lin1.bias", "ffns.6.lin2.weight", "ffns.6.lin2.bias", "ffns.7.lin1.weight", "ffns.7.lin1.bias", "ffns.7.lin2.weight", "ffns.7.lin2.bias", "ffns.8.lin1.weight", "ffns.8.lin1.bias", "ffns.8.lin2.weight", "ffns.8.lin2.bias", "ffns.9.lin1.weight", "ffns.9.lin1.bias", "ffns.9.lin2.weight", "ffns.9.lin2.bias", "ffns.10.lin1.weight", "ffns.10.lin1.bias", "ffns.10.lin2.weight", "ffns.10.lin2.bias", "ffns.11.lin1.weight", "ffns.11.lin1.bias", "ffns.11.lin2.weight", "ffns.11.lin2.bias", "layer_norm2.6.weight", "layer_norm2.6.bias", "layer_norm2.7.weight", "layer_norm2.7.bias", "layer_norm2.8.weight", "layer_norm2.8.bias", "layer_norm2.9.weight", "layer_norm2.9.bias", "layer_norm2.10.weight", "layer_norm2.10.bias", "layer_norm2.11.weight", "layer_norm2.11.bias". 
```

**Comment by alloystory** [comment]
setting the languages to `--lgs 'ar-bg-de-el-en-es-fr-hi-ru-sw-th-tr-ur-vi-zh'`, the number of layers in the transformer to `--n_layers 12` and the max vocab to `--max_vocab 95000` solves the aforementioned issues. the model architecture must mimic the pretrained model's architecture exactly.

**Comment by meeps123** [comment]
Thank you very much!
