### ISSUE TITLE
No file in 'data/wiki' when prepare the data for XLM MLM

### ISSUE THREAD

**Issue by LetsGoFir** [facebookresearch/XLM#310]
But the processing is the same with l.1, and it should have files under 'data/wiki/txt', rather than 'data/wiki'.
The script is confusing.
```
# build the training set for BPE tokenization (50k codes)
OUTPATH=data/processed/XLM_en_zh/50k
mkdir -p $OUTPATH
shuf -r -n 10000000 data/wiki/train.en >> $OUTPATH/bpe.train
shuf -r -n 10000000 data/wiki/train.zh >> $OUTPATH/bpe.train
```
And if I only want to train MLM, is it necessary to run the below commands?
```
pair=en-zh

for lg in $(echo $pair | sed -e 's/\-/ /g'); do
  for split in train valid test; do
    $FASTBPE applybpe $OUTPATH/$pair.$lg.$split data/wiki/para/$pair.$lg.$split $OUTPATH/codes
    python preprocess.py $OUTPATH/vocab $OUTPATH/$pair.$lg.$split
  done
done
```

**Comment by LetsGoFir** [comment]
And for MLM with en and zh, it has an assertion error when 'set_dico_parameters'.
```
WARNING - 07/25/20 21:28:23 - 0:00:00 - Signal handler installed.
INFO - 07/25/20 21:28:23 - 0:00:00 - ============ Monolingual data (en)
INFO - 07/25/20 21:28:23 - 0:00:00 - Loading data from data/processed/XLM_en_zh/50k/train.en.pth ...
INFO - 07/25/20 21:28:35 - 0:00:12 - 2911015899 words (52938 unique) in 45503988 sentences. 0 unknown words (0 unique) covering 0.00% of the data.

INFO - 07/25/20 21:29:01 - 0:00:37 - Loading data from data/processed/XLM_en_zh/50k/valid.en.pth ...
INFO - 07/25/20 21:29:01 - 0:00:37 - 318047 words (52938 unique) in 5000 sentences. 0 unknown words (0 unique) covering 0.00% of the data.

INFO - 07/25/20 21:29:03 - 0:00:39 - Loading data from data/processed/XLM_en_zh/50k/test.en.pth ...
INFO - 07/25/20 21:29:03 - 0:00:39 - 313862 words (52938 unique) in 5000 sentences. 0 unknown words (0 unique) covering 0.00% of the data.

INFO - 07/25/20 21:29:03 - 0:00:39 - ============ Monolingual data (zh)
INFO - 07/25/20 21:29:03 - 0:00:39 - Loading data from data/processed/XLM_en_zh/50k/train.zh.pth ...
INFO - 07/25/20 21:29:06 - 0:00:43 - 330226271 words (66793 unique) in 5949110 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 230, in main
    data = load_data(params)
  File "/data00/home/gongweibo/XLM/src/data/loader.py", line 334, in load_data
    load_mono_data(params, data)
  File "/data00/home/gongweibo/XLM/src/data/loader.py", line 127, in load_mono_data
    set_dico_parameters(params, data, mono_data['dico'])
  File "/data00/home/gongweibo/XLM/src/data/loader.py", line 78, in set_dico_parameters
    assert data['dico'] == dico
AssertionError
```
It seems like it should not be set twice. How to fix it?

**Comment by connectlym** [comment]
Hi,

I met the same issue with you saying the `AssertionError` on `assert data['dico'] == dico`. This is because the `.pth` files should be preprocessed with **the same dictionary(vocabulary)**. In the other words, we should only get the **one** `$OUTPATH/vocab`.

To solve this problem, use this when getting vocab by fastBPE:
`$FASTBPE getvocab $OUTPATH/train.lg1 $OUTPATH/train.lg2 > $OUTPATH/vocab`

Then you should be all set. Hope this could help you!

_reference_: [How to slove this problem load_mono_data assert data['dico'][lang] == mono_data['dico'] AssertionError #75 of facebookresearch/UnsupervisedMT](https://github.com/facebookresearch/UnsupervisedMT/issues/75), [fastBPE](https://github.com/glample/fastBPE#list-commands)

**Comment by hcd7434** [comment]
How are your MLM training results?

**Comment by hcd7434** [comment]
You are training the MLM model. What changes have been made to train.py and trainer.py?
