### ISSUE TITLE
Error when using the uploaded en-fr model for NMT (translate from English to French)

### ISSUE THREAD

**Issue by Anwarvic** [facebookresearch/XLM#342]
Thank you so much for the great effort you put into creating such a powerful model.

When I tried using the en-fr model you uploaded to the [README file](https://github.com/facebookresearch/XLM#pretrained-xlmmlm-models) by running the [command](https://github.com/facebookresearch/XLM/blob/master/translate.py#L11-L15)  suggested in issue #123, it throws the following error:
```
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main(params)
  File "translate.py", line 71, in main
    setattr(params, name, getattr(model_params, name))
AttributeError: 'AttrDict' object has no attribute 'bos_index'
```

**Comment by saikoneru** [comment]
Not sure but seems like they didn't use bos_index from the issue #338. So maybe you could remove the 'bos_index' when reloading the params?
