### ISSUE TITLE
Error in Training

### ISSUE THREAD

**Issue by sadanyh** [facebookresearch/XLM#343]
Hi,

I am getting this error while training. Is it a problem with APEX version? I am working on COLAB and have installed (apex-0.1). Could you please advise on this error?
Thank you

INFO - 12/01/21 16:15:03 - 0:00:02 - Number of parameters (model): 168439772
INFO - 12/01/21 16:15:06 - 0:00:05 - Found 0 memories.
INFO - 12/01/21 16:15:06 - 0:00:05 - Found 12 FFN.
INFO - 12/01/21 16:15:06 - 0:00:05 - Found 198 parameters in model.
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 240, in main
    trainer = SingleTrainer(model, data, params)
  File "/content/XLM/xlm/trainer.py", line 799, in __init__
    super().__init__(data, params)
  File "/content/XLM/xlm/trainer.py", line 58, in __init__
    assert params.amp >= 1 or not params.fp16
AssertionError

**Comment by vicky-yuan** [comment]
Hi, I had the same problem. Did you solve it? Looking forward to your reply!

**Comment by sadanyh** [comment]
Hi, I don't quite remember how I solved the issue. But I followed this notebook:
https://colab.research.google.com/github/Tikquuss/meta_XLM/blob/master/notebooks/demo/tuto.ipynb
This one worked fine.

**Comment by vicky-yuan** [comment]
> Hi, I don't quite remember how I solved the issue. But I followed this notebook: https://colab.research.google.com/github/Tikquuss/meta_XLM/blob/master/notebooks/demo/tuto.ipynb This one worked fine.

Thank you very much, I solved the problem!
