### ISSUE TITLE
Error when using multi-GPU for training MT only

### ISSUE THREAD

**Issue by yuekai146** [facebookresearch/XLM#41]
I tried to train a machine translation model using parallel data only. The script I used for training is as follows:
```
export NGPU=4; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py \
        --exp_name supMT_deen \
        --dump_path ./checkpoints/ \
        --data_path /unsullied/sharefs/zhaoyuekai/data/WMT/corpus/de-en/processed/ \
        --lgs 'de-en' \
        --mt_steps 'de-en' \
        --lambda_mt '0:1,100000:0.1,300000:0' \
         --encoder_only false \
        --emb_dim 1024 \
        --n_layers 6 \
         --n_heads 8 \
         --dropout 0.1 \
         --attention_dropout 0.1 \
         --gelu_activation true  \
         --tokens_per_batch 2000 \
         --batch_size 32 \
         --bptt 256 \
         --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
         --epoch_size 200000 \
         --eval_bleu true \
         --stopping_criterion 'valid_en-fr_mt_bleu,10' \
         --validation_metrics 'valid_en-fr_mt_bleu'
```
When training on only one GPU, no error was reported, however when I tried to train it on 4 GPUs, following error was encountered.
```
Traceback (most recent call last):
  File "train.py", line 341, in <module>
Traceback (most recent call last):
  File "train.py", line 341, in <module>
Traceback (most recent call last):
  File "train.py", line 341, in <module>
Traceback (most recent call last):
  File "train.py", line 341, in <module>
    main(params)
  File "train.py", line 300, in main
    main(params)
  File "train.py", line 300, in main
    main(params)
  File "train.py", line 300, in main
    trainer.mt_step(lang1, lang2, params.lambda_mt)
  File "/unsullied/sharefs/zhaoyuekai/data/XLM/config/XLM.active/src/trainer.py", line 770, in mt_step
    trainer.mt_step(lang1, lang2, params.lambda_mt)
  File "/unsullied/sharefs/zhaoyuekai/data/XLM/config/XLM.active/src/trainer.py", line 770, in mt_step
    trainer.mt_step(lang1, lang2, params.lambda_mt)
  File "/unsullied/sharefs/zhaoyuekai/data/XLM/config/XLM.active/src/trainer.py", line 770, in mt_step
        self.optimize(loss, ['encoder', 'decoder'])self.optimize(loss, ['encoder', 'decoder'])

  File "/unsullied/sharefs/zhaoyuekai/data/XLM/config/XLM.active/src/trainer.py", line 131, in optimize
  File "/unsullied/sharefs/zhaoyuekai/data/XLM/config/XLM.active/src/trainer.py", line 131, in optimize
    self.optimize(loss, ['encoder', 'decoder'])
  File "/unsullied/sharefs/zhaoyuekai/data/XLM/config/XLM.active/src/trainer.py", line 131, in optimize
    main(params)
  File "train.py", line 300, in main
        loss.backward()loss.backward()

  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    loss.backward()
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph)torch.autograd.backward(self, gradient, retain_graph, create_graph)

  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
        allow_unreachable=True)  # allow_unreachable flagallow_unreachable=True)  # allow_unreachable flag

  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
        self._queue_reduction(bucket_idx)self._queue_reduction(bucket_idx)

  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self._queue_reduction(bucket_idx)
  File "/home/zhaoyuekai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
TypeError    : self.device_ids)_queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]
```

**Comment by glample** [comment]
I believe this error happens on recent version of PyTorch Distributed when some parameters (but not all) are updated. Can you try to set `with_output=False` in the encoder construction here? https://github.com/facebookresearch/XLM/blob/master/src/model/__init__.py#L127 When you do MT and not language modeling, the encoder does not need an output layer.

**Comment by stanisz93** [comment]
If I set with_output=False then such an error occurs:
![image](https://user-images.githubusercontent.com/21260980/54590321-24ea6880-4a28-11e9-8a99-cd99ec3fbe9e.png)

**Comment by glample** [comment]
Ah yeah. Sorry about that, I definitely need to deal with the distributed error because this is not convenient. For now can you try to put: `strict=False` in the load_state_dict parameters? It is an option to only reload the available parameters, i.e. everything apart from the pred_layer projection.

**Comment by StillKeepTry** [comment]
I also met this problem as I upgraded PyTorch to `1.0.1.post2` version. It is regular when i use `0.4.1`.

**Comment by odel-odel** [comment]
> Ah yeah. Sorry about that, I definitely need to deal with the distributed error because this is not convenient. For now can you try to put: `strict=False` in the load_state_dict parameters? It is an option to only reload the available parameters, i.e. everything apart from the pred_layer projection.

where can I find he load_state_dict parameters ?

**Comment by stanisz93** [comment]
Sorry for no respond. When I change strict to False it's working :)
