### ISSUE TITLE
The UNMT Training On Multi-GPU Report Errors

### ISSUE THREAD

**Issue by linkerr** [facebookresearch/XLM#95]
**SystemInfo:**
8  Tesla-P100 GPU
torch 1.0.0

parameters is the same to demo.  train the MLM objective is OK,  but train  on unsupervised MT from the pretrained model, it report errors:

**error info:**
loss: tensor(12.0653, device='cuda:0', grad_fn=<MulBackward0>)
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 290, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/workspace/XLM/src/trainer.py", line 821, in mt_step
    self.optimize(loss, ['encoder', 'decoder'])
  File "/workspace/XLM/src/trainer.py", line 131, in optimize
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 96, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 314, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 344, in _queue_reduction
    dev_grads_batch_coalesced = _flatten_dense_tensors(dev_grads_batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 151, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 151, in <listcomp>
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
AttributeError: 'NoneType' object has no attribute 'contiguous'
loss: tensor(12.2142, device='cuda:7', grad_fn=<MulBackward0>)
loss: tensor(12.2979, device='cuda:6', grad_fn=<MulBackward0>)
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 290, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/workspace/XLM/src/trainer.py", line 821, in mt_step
    self.optimize(loss, ['encoder', 'decoder'])
  File "/workspace/XLM/src/trainer.py", line 131, in optimize
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 96, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 314, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 344, in _queue_reduction
    dev_grads_batch_coalesced = _flatten_dense_tensors(dev_grads_batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 151, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 151, in <listcomp>
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
AttributeError: 'NoneType' object has no attribute 'contiguous'
loss: tensor(12.4510, device='cuda:1', grad_fn=<MulBackward0>)

I also try to train  on unsupervised MT from the pretrained model with single GPU, it's ok. I have no idea how to resolve the error.

**Comment by glample** [comment]
This looks like some kind of errors you get when you use distributed training, and that some of the parameters are not used in the forward path. This problem was fixed in PyTorch 1.1.0 I believe. If you want to stick to PyTorch 1.0.0 can you try setting `with_output=False` for the encoder line in:
https://github.com/facebookresearch/XLM/blob/master/src/model/__init__.py#L127
And see if you still have the issue?

**Comment by linkerr** [comment]
@glample  Thank you very much, thank you !

I  try the two methods, all is ok.  
 in PyTorch 1.1.0 add the parameter _find_unused_parameters=True_ for DistributedDataParallel train in:
[https://github.com/facebookresearch/XLM/blob/master/train.py#245](https://github.com/facebookresearch/XLM/blob/master/train.py#245)

**Comment by glample** [comment]
Thanks for checking that it's fine with `find_unused_parameters=True` :)

**Comment by bakszero** [comment]
Hi @linkerr , I updated my Pytorch version to 1.1.0 and even set the parameter `find_unused_parameters=True` in my  train.py file for the 'pre-training step' , not fine-tuning one.

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=0', '--exp_name', 'pt_xlm_abl', '--dump_path', './dumped', '--data_path', './XLM_en_abl/10k/', '--lgs', 'abl', '--clm_steps', '', '--mlm_steps', 'abl', '--emb_dim', '512', '--n_layers', '12', '--n_heads', '16', '--dropout', '0.1', '--attention_dropout', '0.1', '--gelu_activation', 'true', '--batch_size', '16', '--bptt', '256', '--optimizer', 'adam,lr=0.0001', '--tokens_per_batch', '2000', '--epoch_size', '30000', '--max_epoch', '1000000', '--stopping_criterion', '_valid_mlm_ppl,40', '--save_periodic', '20']' died with <Signals.SIGKILL:9>.`

and also 

`Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main(params)
  File "train.py", line 245, in main
    model = nn.parallel.DistributedDataParallel(model, device_ids=[params.local_rank], output_device=params.local_rank, broadcast_buffers=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: Broken pipe`

I have looked at https://github.com/facebookresearch/XLM/issues/109 and the solution there doesn't work either. Any pointers?

**Comment by ethanjperez** [comment]
@bakszero there's some other discussion here which worked for me: https://github.com/facebookresearch/XLM/issues/41
